### DISCUSSION TITLE
How To Insert a Non Yaml file with Ytt

### DISCUSSION THREAD

**Discussion by ghost** [k14s/ytt#359] [Q&A] [answered]
Im looking for a way in ytt to easily do the following (pseudocode).

I can see that `ytt` already has a `load()` but this assumes the input file is already yaml.. my use case is different. 

```
eg - is there any thing like this in ytt
configmap:
   name: something
   data: |
      @ytt include "nginx.config" 
```

Currently I have this working with `sed` which works ok , but it is clunky and means a preprocessing phase, ideally I would  like to just have `ytt` handle the injection as `ytt` would also indent the file correctly.  
Currently I have to indent  "nginx.conf" correct before I inject it which is not ideal.
```
configmap:
   name: something
   data: |
      %%nginx-conf%%
      
sed -e  '/%%nginx_conf%%/r ./nginx.conf' -e 's/%%nginx_conf%%//g' configmap.yaml | ytt ... blah blah
```

**Comment by cppforlife** [comment]
as long as your ytt invocation includes necessary file (nginx.conf) in -f flags, then you can use `data.read(...)` function. example: https://carvel.dev/ytt/#example:example-load-data-files

invocation would look something like this `ytt -f nginx.conf -f configmap.yml` or if they are in the same directory `ytt -f stuff/`.

on a chance that you need to template variables inside nginx.conf itself take a look at text templating example: https://carvel.dev/ytt/#example:example-text-template

**Comment by ghost** [comment]
Thanks for this.

using this markup...results 
```
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ files = data.list()

#@overlay/match by=overlay.all, expects="1+"
---
configMaps:
#@overlay/match by="name"
- name: a-configmap
  data:
      #@overlay/match missing_ok=True
      nginx-conf:
      #@ for/end file in [ f for f in files if f.endswith(".conf") ]:
      - #@ data.read(file)
 ```
 results in 
 
 ```
nginx-conf: 
        - |-
            user       www www;  ## Default: nobody
            worker_processes  5;  ## Default: 1
            error_log  logs/error.log;
            pid        logs/nginx.pid;
            worker_rlimit_nofile 8192;
```
     
   notice the 
  ```
 nginx-conf: 
       - |-
           stuff
```
 How do i get just
```
    nginx-conf: |
       stuff
```

**Comment by cppforlife** [comment, marked as answer]
the reason why you are getting array item is because you are specifying to add this content as an array item (ie dash in YAML adds an array item in `- #@ data.read(file)`). if you just have a single file called nginx.conf it should just be:

```yaml
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.all, expects="1+"
---
configMaps:
#@overlay/match by="name"
- name: a-configmap
  data:
      #@overlay/match missing_ok=True
      nginx-conf: #@ data.read("nginx.conf")
```

if you are actually trying to "combine" all files that end with .conf, then it could be like this (uses comprehensions)

```yaml
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.all, expects="1+"
---
configMaps:
#@overlay/match by="name"
- name: a-configmap
  data:
      #@overlay/match missing_ok=True
      nginx-conf: #@ "\n".join([ data.read(f) for f in data.list() if f.endswith(".conf") ])
```
