### DISCUSSION TITLE
Load data values into both

### DISCUSSION THREAD

**Discussion by darrenjl0** [k14s/ytt#663] [Q&A] [answered]
Hello,
From my reading, it appears there is no way for a library to fetch an external data.value, without referring to the value directly within the definition ?
I'm new to YTT as you will probably be able to tell. If I am way of the mark let me know and I'll go back to drawing board.

## Brief overview of setup
```
Top Level
shared/_ytt_lib
deployments /{UK | US} >
              UK/groupfoo/{app1.yml | app2.yml }
              UK/globals/{env1.yml | env2.yml }
```

### uk/groupfoo/app1.yml
```
#@ load("@ytt:template", "template")
#@ load("@ytt:library", "library")
#@ load("@ytt:data", "data")
#@ def app_deploy():

name: nginx-test
port: 80
namespace: default
image: docker.io/nginx:1.21.6
ingress: internal
replicas: 5

env_config:
  test1: test
  key1: this-service.com
  key2: #@ data.values.currency


#@ end
#@ app = library.get("foolib/app").with_data_values(app_deploy())
--- #@ template.replace(app.eval())
```

### uk/global/env1.yml
```
#@data/values-schema
---
domain: foo.com
currency: £
```

The library requiring `domain` as an input. Eg `ingress: #@ return service_name() + "." + data.values.domain`
```
ytt -f UK/groupfoo/ -f UK/globals/env1.yml -f shared/ 
```
