### ISSUE TITLE
ytt strips out AWS SAM template `!Ref`, `!Sub`, etc. directives out of my values

### ISSUE THREAD

**Issue by SnarfleBunny** [k14s/ytt#104]
Is there a way I can keep those in the output YAML?

I have a subdir named `etc/` which has this file in it:

```yaml
#@ load("@ytt:data", "data")
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FOS REST API

#! Parameters

Parameters:

  DeployEnv:
    Type: String
    Default: #@ data.values.deploy_env
  UsagePlanType:
    Type: String
    Default: PER_API

#! Conditions

#! Globals

Globals:
  HttpApi:
    Auth:
      ApiKeyRequired: true
      UsagePlan:
        CreateUsagePlan: !Ref UsagePlanType

#! Resources

Resources:


  FosRestApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref DeployEnv


#! Outputs

```

Here is `values.yml`:
```yaml
#@data/values
---
deploy_env: dev
```

The following is what it produces:

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: FOS REST API
Parameters:
  DeployEnv:
    Type: String
    Default: dev
  UsagePlanType:
    Type: String
    Default: PER_API
Globals:
  HttpApi:
    Auth:
      ApiKeyRequired: true
      UsagePlan:
        CreateUsagePlan: UsagePlanType
Resources:
  FosRestApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: DeployEnv
```

You will notice all the `!Ref` s are removed from the output. How do I let those directives remain in the output?
