### ISSUE TITLE
[data/values] Ability to read in multiple separate "values" files

### ISSUE THREAD

**Issue by aegershman** [k14s/ytt#11]
Apologies if this is something already covered with the documentation, _but_:

Is there a way to pass in multiple `values` files into a template? I'm trying to separate out configuration for `values` into multiple files rather than one big-honkin' single file, though I'm unsure if this is supported or how to properly reference multiple data files. With that said, having a single `values.yml` isn't horrible and may be preferable. But what I'm trying to do is hierarchical overriding, e.g.:

```
.
├── envs
│   ├── aws
│   │   ├── dev
│   │   │   └── values.yml
│   │   ├── sandbox
│   │   │   └── values.yml
│   │   └── values.yml
│   ├── values.yml
│   └── vsphere
│       ├── dev
│       │   └── values.yml
│       ├── sandbox
│       │   └── values.yml
│       └── values.yml
└── template.yml
```

... and extract out "common" values into the appropriate hierarchical level, e.g. global values defined under `envs/`, "vsphere"-related values in `envs/vsphere`, etc. and the values are overridden as you get closer to the specific values file you're trying to use.

Advice and/or feedback is appreciated, thank you for your time.

**Comment by cppforlife** [comment]
@nimakaviani and i earlier on were discussing offering ability to specify [overlay](https://github.com/k14s/ytt/blob/master/docs/lang-ref-ytt-overlay.md) configuration for data/values. it could look something like this:

`values.yml`

```yaml
#@data/values
---
val1: one
val2: two
```

`aws/dev/values.yml`

```yaml
#@ load("@ytt:data", "data")
#@overlay/match by=data.values_document
---
val1: two
#@overlay/remove
val2:
```

which would ultimately result in `@data/values`:

```yaml
val1: two
```

before processing rest of the templates.

wdyt? it sounds like it would allow you to

**Comment by cppforlife** [comment]
reminder to self: ordering of overlays was in question here.

**Comment by cppforlife** [comment]
current thinking is to mark overlay documents with `@data/values` as well

```yaml
#@ load("@ytt:overlay", "overlay")
#@ load("@github.com:blah", "blah")
#@data/values
#@overlay/match ...
---
#@overlay/match missing_ok=True
key: foo
#@overlay/match missing_ok=True
blah: #@ blah.something
```

not sure though how to indicate it's an overlay if `@overlay/match` doesnt take any args.

marking overlays with data/values helps to identify which files should be templated to obtain data.values.
