### ISSUE TITLE
[data] data.list() can't see files outside of the directory where it's called

### ISSUE THREAD

**Issue by olivier-mauras** [k14s/ytt#113]
``` yaml
#! base/templates/configmaps.yaml
#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: #@ 'configmap-' + data.values.name
data: #@ data.list()
```
```
$ ytt -f base/ -f custom/ -f values.yml --files-inspect
- defaults.yml
- libs/helpers.lib.yml
- libs/helpers.star
- templates/configmaps.yaml
- templates/deployment.yml
- templates/ingress.yml
- templates/service.yml
- configmaps/dev/xx.cfg
- values.yml

$ ytt -f base/ -f custom/ -f values.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-devapi-test
data:
- templates/configmaps.yaml
- templates/deployment.yml
- templates/ingress.yml
- templates/service.yml
```
