### ISSUE TITLE
How to insert/merge multi-level block?

### ISSUE THREAD

**Issue by jiatongw** [k14s/ytt#129]
Hi, I am trying to insert a multi-level level block to an original yaml file:

original:
```
apiVersion: test
kind: test
metadata:
  name: test
  namespace: test
spec:
  infrastructureTemplate:
    apiVersion: test
    kind: test
    name: test
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
```

the patch file would be:

spec:
```
metadata:
  name: test
  namespace: test
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      imageRepository: test
      kubernetesVersion: test
        - etcd:
            local:
              dataDir: test
              imageRepository: test
              imageTag: test
```

the combination would be:
<pre>
apiVersion: test
kind: test
metadata:
  name: test
  namespace: test
spec:
  infrastructureTemplate:
    apiVersion: test
    kind: test
    name: test
  kubeadmConfigSpec:
    clusterConfiguration:
      <b>imageRepository: test
      kubernetesVersion: test
        - etcd:
            local:
              dataDir: test
              imageRepository: test
              imageTag: test</b>
      apiServer:
        extraArgs:
          cloud-provider: external
</pre>

But I tried `overlay` method but it doesn't work with a multi-level insert. Can I get some guidance on how to do this? Thanks!

**Comment by ewrenn8** [comment]
Hi @jiatongw,

The overlay package is exactly what you're looking for! Although it seems like you have invalid yaml in your example, more specifically, the block:
```yaml
...
clusterConfiguration:
      imageRepository: test
      kubernetesVersion: test
        - etcd:
            local:
              dataDir: test
              imageRepository: test
              imageTag: test
...
``` 
Is invalid at the `- etcd` line. This array item needs to be in an array but is currently in a map.

I have added `<some-key>` as the container for the array item but otherwise, this is an example of using the overlay package to achieve what you've described: https://get-ytt.io/#gist:https://gist.github.com/ewrenn8/e61a6234ea175eec7958be76dc2ebfea.
