### ISSUE TITLE
overlay merge issue (merging map on top of nil)

### ISSUE THREAD

**Issue by RadhaR4** [k14s/ytt#137]
I want to merge below two yamls in ytt,
```

#! Base
#@ def namespaces_left():
namespaces:
  testns:
  default:
  monitoring:
#@ end
```

---
#! Overlay
```
#@ def namespaces_right():
#@overlay/match-child-defaults missing_ok=True
#@overlay/merge
namespaces: 
  testns: 
    protected: false
  newns:
#@ end
```

---

namespaces: #@ overlay.apply(namespaces_left(),namespaces_right())

I am expecting result as below which is the merged output of namespaces present in base and overlay
```
namespaces:
  testns:
    protected: false
  default:
  monitoring:
  newns:
```

But I am getting error as below,
```
- overlay.apply: Map item (key 'namespaces') on line dsfoverlay.yaml:141: Map item (key 'testns') on line dsfoverlay.yaml:142: Expected map, but was <nil>
    in <toplevel>
      dsfoverlay.yaml:148 | namespaces: #@ overlay.apply(namespaces_left(),namespaces_right())

```
How to use overlay for this?

**Comment by cppforlife** [comment]
overlay module does not allow merging map (rightside) into nil (leftside): https://github.com/k14s/ytt/issues/108 (per error message that's the value of testns key in this example). currently you would have to use overlay/replace annotation on top of testns to entirely replace that key-value.

```yaml
#@ def namespaces_right():
#@overlay/match-child-defaults missing_ok=True
namespaces: 
  #@overlay/replace
  testns: 
    protected: false
  newns:
#@ end
```
