### ISSUE TITLE
Iterating through data values for overlay

### ISSUE THREAD

**Issue by KR411-prog** [k14s/ytt#138]
I have my base file as below,
```

#@data/values
---
namespaces: 
    testns:
       protected: false
    test: 
apps:
  app1:
    enabled: false
  app2:
    enabled: true
```
====================================
Overlay file as below,
```

#@ def namespaces_left():
namespaces:
    testns:
       newproperty: prop1
    default:
#@ end

#@ def namespaces_right():
#@overlay/match-child-defaults missing_ok=True
namespaces: 
  #@overlay/merge
     (Question?---> How to iterate over all the elements from data.values.namespaces here?)
  newns:
#@ end

`namespaces: #@ overlay.apply(namespaces_left(),namespaces_right())["namespaces"]`

```
In this issue that I have raised  #137  ,I have hardcoded the data.values file namespace content.Now I want to pick up from the data.values file by iterating through the namespaces.

**Comment by cppforlife** [comment]
here is an example of iteration: https://gist.github.com/cppforlife/935f06c80e71ff83926676e74132eec7. as of now you have to use struct module to convert data.values into something thats iterable; however, we have plans to be able to do `for x in data.values.namespaces:` directly.

**Comment by cppforlife** [comment]
move concretely:

```yaml
#@ load("@ytt:data", "data")
#@ load("@ytt:struct", "struct")

#@ nss = struct.decode(data.values.namespaces)

images:
  #@ for/end ns in nss:
  #@yaml/text-templated-strings
  (@= ns @):
    something: ...
```

**Comment by RadhaR4** [comment]
Thankyou for the prompt response..I will try this..

**Comment by RadhaR4** [comment]
It worked partially for my usecase..

```
#@ def namespaces_right():
#@overlay/match-child-defaults missing_ok=True
#@ nss = struct.decode(data.values.namespaces)
namespaces:
  #@ for/end ns in nss:
  #@overlay/merge
  #@yaml/text-templated-strings
  (@= ns @): 
#@ end
```
the data.values file contains some child elements like below,

```
#@data/values
---
namespaces: 
    testns:
       protected: false
    test: 
```
So the code has to also iterate through all the child elements to merge..
Like.. 
  (@= ns @):  ns.getallkeys() 
Basically I am trying to get the entire namespace with its keys and values from data/values file in the overlay so i can merge it with my base.data/values is where the user customizes their config..

Please let me know how to get all the keys and their values from data/values

**Comment by cppforlife** [comment]
im getting a little lost here to be honest on what you are trying to do. can you provide 3 pieces of yaml: base, data values and expected result.

**Comment by RadhaR4** [comment]
Sorry if I was not clear..
**Base:**
```
#@data/values
---
namespaces: 
    testns:
       protected: false
       dynamicproperty1: prop1
    test:
```

**Overlay:**
```
#@ def namespaces_left():
namespaces:
  testns:
  default:
#@ end

#@ def namespaces_right():
#@overlay/match-child-defaults missing_ok=True
#@ nss = struct.decode(data.values.namespaces)
namespaces:
  #@ for/end ns in nss:
  #@overlay/merge
  #@yaml/text-templated-strings
  (@= ns @): 
       #@ if/end  "protected" in nss[ns]:  (Question----->if I want to fetch all the keys and subkeys and their values from data.values file how to do that? Example:dynamicproperty1 in the data values file needs to be merged )
       protected: #@ nss[ns]["protected"] 
#@ end
```

**Expected output:**
```
namespaces: 
    testns:
       protected: false
       dynamicproperty1: prop1
    test:
    default:
```
