### ISSUE TITLE
[question] overlays: Replace with a variable and delete a field

### ISSUE THREAD

**Issue by jiatongw** [k14s/ytt#142]
Hi, I have a hard time reading the examples and didn't found a resolution. What I am trying to do is two operations: delete and replace
assuming I have a `deployment.yaml`, which the content would be:
```
apiVersion: app/v1
kind: deployment
metadata:
  name: '${ CLUSTER_NAME }'
  namespace: '${ NAMESPACE }'
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    clone: true
```
I want to replace `- 192.168.0.0/16` with a variable `'${SUBNET}'`, and then I want to delete `clone:true`, which the result would be a `new_deployment.yaml`:

```
apiVersion: app/v1
kind: deployment
metadata:
  name: '${ CLUSTER_NAME }'
  namespace: '${ NAMESPACE }'
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - '${SUBNET}'
```
How should I do that? 
Also, for `ytt` command, I have to put some changes in a `config.yaml` and then run something like `ytt -f config.yaml -o new_deployment.yaml`?

Thanks.

**Comment by cppforlife** [comment]
here is an example of how to do with overlays: https://get-ytt.io/#gist:https://gist.github.com/cppforlife/8ec9766f4b9193a442a27bfaaebfb3f1 ([overlay docs](https://github.com/k14s/ytt/blob/master/docs/lang-ref-ytt-overlay.md)). invocation would be something like `ytt -f config.yml -f mods.yml > result.yml`

**Comment by jiatongw** [comment]
Hi @cppforlife , in the result 
```
apiVersion: app/v1
kind: Deployment
metadata:
  name: ${ CLUSTER_NAME }
  namespace: ${ NAMESPACE }
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - ${SUBNET}
```
where `${SUBNET}` isn't have quotes, so it is not a variable but a string? the same problem as ${ CLUSTER_NAME } and ${ NAMESPACE }

**Comment by cppforlife** [comment]
ytt uses yaml library which serializes yaml structures according to the yaml spec. it also happens to pick some canonical representation. in this case, in yaml, `'${ CLUSTER_NAME }'` is not in its canonical form because there is no need to have quotes (according to yaml spec) hence when it serializes it, no quotes are added.

> so it is not a variable but a string

there is no concept of a variable in plain yaml. quotes or no quotes there are both strings from yaml perspective.

**Comment by cppforlife** [comment]
for the sake of completeness here is how i would write template to use ytt data values: get-ytt.io/#gist:https://gist.github.com/cppforlife/5895390e6944fbf6a14eaae0b5767bef

**Comment by jiatongw** [comment]
@cppforlife Ohhh, I see. Let me try the above example and I'll report back if I have any further questions. Thanks!

**Comment by jiatongw** [comment]
@cppforlife I got two questions regarding replacing elements.
1. for replacing in array items:
```
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - args:
        image: image-1
        name: image-1
        ports:
        - containerPort: 8443
          name: https
      - args:
        image: image-2
        imagePullPolicy: IfNotPresent
```
so I want to use the `replace` method to replace both the image fields under container key:
```
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - args:
        image: image-3
        name: image-3
        ports:
        - containerPort: 8443
          name: https
      - args:
        image: image-4
        imagePullPolicy: IfNotPresent
```
could you give me an example how to do this?

2. for the `|-` symbol in yaml.
the original content is:
```
apiVersion: v1
kind: Secret
stringData:
  credentials.yaml: |-
    username: 123
    password: 123
```
After replace, I got:
```
apiVersion: v1
kind: Secret
stringData:
  credentials.yaml: "username: 456\npassword: 456\n  "
```
I know this is right, but how can I get a more readable result like:
```
apiVersion: v1
kind: Secret
stringData:
  credentials.yaml: |-
    username: 456
    password: 456
```

**Comment by cppforlife** [comment]
1. below overlay shows how to match array element by a subset

```yaml
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"apiVersion":"apps/v1", "kind": "Deployment"})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by=overlay.subset({"image": "image-1"})
      - name: image-3
        image: image-3
      #@overlay/match by=overlay.subset({"image": "image-2"})
      - image: image-4
```

2. multi-line formatting

```yaml
stringData:
  credentials.yaml: "username: 456\npassword: 456\n  "
```

the reason why it's formatted this way is because there is trailing space. there is no way to represent that within yaml on multiple lines hence double quotes are used. if you make sure that there is no space at the end, it will use multi-line format. (though i would recommend to not bother hunting down yaml formatting decisions, since it's valid yaml anyway)
