### ISSUE TITLE
[lang] support multiline arguments to annotations

### ISSUE THREAD

**Issue by cppforlife** [k14s/ytt#149]
For example,

```yaml
#@doc """
#@ something something
#@ """
a: 123

#@overlay/match by=overlay.subset({
#@  "kind": "Foo",
#@  "metadata": {"blah": "blah"},
#@ })
b: 123
```
