### ISSUE TITLE
[data/values] ability to iterate over data.values keys (not possible since it's a struct and there is no `keys()`)

### ISSUE THREAD

**Issue by brightzheng100** [k14s/ytt#15]
It's common to extract some keys and/or values from existing yaml files.

For example, given a product config file:

```
#! products.yml
products:
  product-1: xxx
  product-2: xxx
```

It'd be cool to extract all products out as an array, here might be `["product-1", "product-2"]`, so that I can do something like:

```
#@ load("@ytt:extract", "extract")

product-info:

#@ for product in (extract("products.yml", "products")):
- name: #@ product
#@ end

```

**Comment by nimakaviani** [comment]
good point. ideally, you should be able to use `.keys()` on a dictionary object to extract the keys.

the following already works:

```
#@ dict = {"a": 1, "b": 2}

#@ for/end d in dict.keys():
- name: #@ d
``` 
and produces:
```
- name: a
- name: b
```

However, with the following data file

```
#@data/values
---
dict:
  a: 1
  b: 2
```

`.keys()` should continue to work when used like below and produce an output similar to the above.

```
#@ load("@ytt:data", "data")

#@ for/end d in data.values.dict.keys():
- name: #@ d
```

we will look into it.

**Comment by cppforlife** [comment]
if this helps, following works in interactive playground (https://get-ytt.io):

```
#@data/values
---
products:
- name: first
  price: 70
- name: second
  price: 100
```

and to read array from data values:

```
#@ load("@ytt:data", "data")

store:
#@ for r in data.values.products:
- #@ "Buy " + r.name + " for " + str(r.price)
#@ end
```

currently we dont support `keys()` and similar methods because there is a naming ambiguity for accessing method vs field (since we allow field syntax (`r.name`) instead of bracketed syntax `r["price"]`). i wonder if we should provide `struct.to_dict(data.values.something)` (in struct library) that would convert struct into a dict.
