### ISSUE TITLE
Error: have either computed or YAML value, but found both

### ISSUE THREAD

**Issue by colin-mccarthy** [k14s/ytt#158]
Trying to understand what this error means and how to resolve it.

Error:

Compiling YAML template 'test.yml': Expected YAML node at line test.yml:23 to have either computed or YAML value, but found both

```

#@ def labels():
tower_username: admin
tower_password: "{{ admin_password }}"
tower_host: "{{ ansible_host }}"
tower_verify_ssl: false 
#@ end

---
- name: Tower Projects
  hosts: tower
  gather_facts: false
  connection: local
  collections: 
    - awx.awx
    
    
 

  tasks:
  - name: CREATE ORGANIZATION
    awx.awx.tower_organization: #@ labels()
      name: "{{ organization }}"
      description: "{{ organization }}"
 
```

Expected : 

```

---
- name: Tower Projects
  hosts: tower
  gather_facts: false
  connection: local
  collections: 
    - awx.awx
    
    
 

  tasks:
  - name: CREATE ORGANIZATION
    awx.awx.tower_organization: 
      tower_username: admin
      tower_password: "{{ admin_password }}"
      tower_host: "{{ ansible_host }}"
      tower_verify_ssl: false 
      name: "{{ organization }}"
      description: "{{ organization }}"
```

**Comment by ewrenn8** [comment]
Hey @colin-mccarthy,

As it is written right now, the value of the `awx.awx.tower_organization` key is getting both the computed value `labels()` as well as some children values. ytt does not know which of these to use, so it errors. To achieve the output you want, you would need to us the `template` package's replace function, like so:

```
#@ load("@ytt:template", "template")

#@ def labels():
tower_username: admin
tower_password: "{{ admin_password }}"
tower_host: "{{ ansible_host }}"
tower_verify_ssl: false 
#@ end

---
- name: Tower Projects
  hosts: tower
  gather_facts: false
  connection: local
  collections: 
    - awx.awx
  tasks:
  - name: CREATE ORGANIZATION
    awx.awx.tower_organization:
      _: #@ template.replace(labels())
      name: "{{ organization }}"
      description: "{{ organization }}"
```
