### ISSUE TITLE
Support dynamic keys

### ISSUE THREAD

**Issue by bosix** [k14s/ytt#165]
Hi,
I found yrr a few days ago and was amazed about the possibilities the tool has. Currently, I'm trying to transform our gitlab-ci.yml-files into something which can be reused better. In such file you often have a section like this ():

```yaml
deploy:develop:
    script: ./bin/deploy/devlop.sh

deploy:staging:
    script: ./bin/deploy/staging.sh

deploy:productive:
    script: ./bin/deploy/productive.sh
```

This example is simplified but shows why I want to use a template for this file :). Therefore I create a values-file with the following content:

```yaml
#@data/values
---
deployments:
    -   name: develop
        script: ./bin/deploy/develop.sh
    -   name: staging
        script:./bin/deploy/staging.sh
    -   name: productive
        script:./bin/deploy/productive.sh
```

My problem is that I have to set the key of the struct so I tried this:

```yaml
#@ load("@ytt:data", "data")

#@ for deployment in data.values.deployments:
#@ "deploy:" + deployment.name + ":"
    script: #@ deployment.script
#@ end
```

Well, this do not work since I have to set the key (which is top level/root) dynamically. Does anybody have an idea of how to achieve dynamic keys based on values?

**Comment by cari-lynn** [comment]
Hi @bosix, this is an interesting use case, thanks for sharing it.
You can achieve this by using `template.replace()` combined with a function. [Here's](https://get-ytt.io/#gist:https://gist.github.com/pivotal-dean/2da8a5fabf681638f2ce6f8e3afaadc9) an example. 
Let us know if that's not what you're looking for.

**Comment by bosix** [comment]
Hi @pivotal-dean,

this is exactly what I was looking for. Thank you for your help.

**Comment by cppforlife** [comment]
@bosix here is another way, arguably more yaml-y: https://get-ytt.io/#example:example-text-template (see line config.yml:23)

**Comment by bosix** [comment]
@cppforlife thank you. I agree with you. In my case, I think your suggestion is cleaner and more readable.

**Comment by matthewcosgrove** [comment]
Also trying something similar for creating Ansible inventory yaml on the fly.

The first approach suggested above works well enough
(https://www.get-ytt.io/#gist:https://gist.github.com/matthewcosgrove/6cdee88fb804150ef2708e015b6bbc96)

```
#@ load("@ytt:data", "data")
#@ load("@ytt:template", "template")

#@ def parse(deployment):
#@ key = "{}".format(deployment.ip)
#@ return {key: {"idrac_ip": "{{ inventory_hostname }}","catalog_xml": deployment.catalogXml}}
#@ end

all:
  hosts:
#@ for deployment in data.values.deployments:
    _: #@ template.replace(parse(deployment))
#@ end
```
with values
```
#@data/values
---
deployments:
- ip: 10.0.0.1
  catalogXml: "Catalog1.xml"
- ip: 10.0.0.2
  catalogXml: "Catalog2.xml"
```

Based on the comment from @cppforlife I'm wondering is there a better way to do this more yaml-y? I took at a look at the suggested example https://get-ytt.io/#example:example-text-template (line config.yml:23) but couldn't correlate it to the desired result

```
all:
  hosts:
    10.0.0.1:
      idrac_ip: '{{ inventory_hostname }}'
      catalog_xml: Catalog1.xml
    10.0.0.2:
      idrac_ip: '{{ inventory_hostname }}'
      catalog_xml: Catalog2.xml
```
