### ISSUE TITLE
Merge list when right-side is sometimes nil

### ISSUE THREAD

**Issue by taylorsilva** [k14s/ytt#168]
_While trying to make a reproducible I ran into an issue and can't figure out what's wrong with my example YAML below. I mirrored what I'm doing with my much larger yaml where my issue originates from._

I have a situation where I have a list and I want to call a function to optionally add to that list. Sometimes the second list may be nil. Here's a reproducible.

* list.yaml
```yaml
#@ load("@ytt:template", "template")

#@ def other_items(distro):
#@ if distro == "ubuntu":
- "ubuntu-item"
#@ end
#@ end

#@ def the_list(distro):
my_list:
- "item1"
- "item2"
- #@ template.replace(other_items(distro))
other_content:
  not_related: "to the above list"
#@ end

---
final-list:
  - #@ the_list("alpine")
  - #@ the_list("ubuntu")
```

_Apologies, I can't figure out wtf is wrong with the above YAML. I get this error:_
```
$ ytt -f ./
ytt: Error: Unmarshaling YAML template 'list.yml': yaml: line 9: did not find expected '-' indicator
```

If the above YAML was working I'm expecting the following error:
```
- template.replace: expected value to be array, but was <nil>
```

Again, sorry the example doesn't work. Regardless, am I going about this the right way?
