### ISSUE TITLE
Splitting function parameters over multiple lines

### ISSUE THREAD

**Issue by peterfeifanchen** [k14s/ytt#170]
Hi, I was wondering for a ytt func:

`def func(a,b,c):
  ...
  end`

Is there a way to call it such that I can have the parameters spread over multiple lines?

`key: #@ func(a,
                         b,
                         c)
`

**Comment by ewrenn8** [comment]
Hey @peterfeifanchen,

Unfortunately, ytt doesn't currently support multiline annotations. We have #149 to implement this but have not prioritized it. Is there a reason beyond readability or long arguments that you'd like to split arguments?

Eli

**Comment by peterfeifanchen** [comment]
No it's just for readability reasons.

**Comment by cppforlife** [comment]
you can do following meanwhile

```yaml
#@ def foo(a,b,c,d):
a: #@ a
b: #@ b
c: #@ c
d: #@ d
#@ end

#@ args = (
#@   1,
#@   2,
#@   3,
#@   4,
#@ )

foo: #@ foo(*args)
```

or other variations like

```yaml
#@ args = (1, 2,
#@   3, 4,)
```
