### ISSUE TITLE
Add support for templating blocks

### ISSUE THREAD

**Issue by gerhard** [k14s/ytt#177]
Given `template.yml`

```yaml
#@ load("@ytt:data", "data")
foo: #@ data.values.foo
literal_block: |
  foo: #@ data.values.foo
```

And `values.yml`

```
#@data/values
---
foo: bar
```

Red is what ytt 0.28.0 does currently, green is what I would expect it to do:

```diff
ytt -f template.yml -f values.yml
foo: bar
literal_block: |
-  foo: #@ data.values.foo
+ foo: bar
```

**Comment by ewrenn8** [comment]
Hi @gerhard,

Ytt supports this use case through text templating. Here is how you would use it with your example: https://get-ytt.io/#gist:https://gist.github.com/ewrenn8/66ec1625862fd741e93f8dfdf0b82509

Eli

**Comment by cppforlife** [comment]
however, text templating isnt great for structured data (in your example it looks like yaml). here is what i would recommend:

```yaml
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ def block():
foo: #@ data.values.foo
#@ end

foo: #@ data.values.foo
literal_block: #@ yaml.encode(block())
```

here is example https://github.com/k14s/ytt/tree/develop/examples/k8s-config-map-files
