### ISSUE TITLE
[data/values] data values are parsed as strings by default

### ISSUE THREAD

**Issue by NoiSek** [k14s/ytt#179]
**Summary:**
Passing integer values in through the use of `--data-values-env` will cause errors due to ytt rendering them later on as strings. 

Tangentially related to #103 and the [accompanying typing proposal](https://github.com/k14s/ytt/tree/develop/proposals/001-schemas).

**Expected Behavior:**
The parser should preserve the integer state of parsed environment variables and / or the renderer should support the ability to cast a given value to an integer at runtime.

(i.e. `#@ int:data.values.foobar` or similar)

**Actual Behavior:**
Values set through environment variables such as `CFG_http_port=8080` will be resolved as `"8080"` when used, which causes errors later on against tools that validate the types of fields that use those values.

**Steps to reproduce:**
- `export CFG_test=8080`
- `ytt -f foo/values.yaml -f foo/bar.yaml --data-values-env CFG`
- Observe that the value of `casted-value` is now a quoted string.
- `ytt -f foo/values.yaml -f foo/nginx.yaml --data-values-env CFG | kapp -y deploy -a my-app -f -`
- Observe the validation / build errors that occur.

`foo/values.yaml`:
```
#@data/values
---
test:
```

`foo/bar.yaml`:
```
#@ load("@ytt:data", "data")
casted-value: #@ data.values.test
```

`foo/nginx.yaml`:
```
#@ load("@ytt:data", "data")
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: #@ data.values.test
```

Building an actual container through Kapp will give you an error similar to:
```
Invalid value: "string": spec.datacenter.racks.members in body must be of type integer: "string" (reason: Invalid)
```

Or:
```
Service in version "v1" cannot be handled as a Service: v1.Service.Spec: v1.ServiceSpec.Ports: []v1.ServicePort: v1.ServicePort.Port: readUint32: unexpected character: �, error found in #10 byte of ...|","port":"8080","tar|..., bigger context ...|IP":"10.105.7.57","ports":[{"name":"http","port":"8080","targetPort":"8080"}],"selector":{"app":"dja|... (reason: BadRequest)
```
