### ISSUE TITLE
No access to key

### ISSUE THREAD

**Issue by 2shsh** [k14s/ytt#181]
I want to migrate from helm to ytt.
In my values.yaml i have next part:
``` yaml
services:
  app1:
    command: ['/bin/tel']
    port: 5000
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/metrics"
      prometheus.io/port: "5000"
    replicas: 2
    resources:
      requests:
        cpu: 0.15
        memory: 600Mi
      limits:
        cpu: 1
        memory: 800Mi
  app2:
    command: ['/bin/tel-consumer']
    port: 5000
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/metrics"
      prometheus.io/port: "5000"
    replicas: 2
    resources:
      requests:
        cpu: 0.15
        memory: 600Mi
      limits:
        cpu: 1
        memory: 800Mi
```
My template file looks like:
``` yaml
#@ load ("@ytt:data", "data")
#@ load("@ytt:struct", "struct")

#@ services = struct.decode(data.values.services)
#@ for service in services:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ service
  labels:
    release: #@ data.values.app
    app: #@ service
spec:
  #@ replicas = services[service]["replicas"]
  #@ if replicas:
  replicas: #@ replicas
  #@ else:
  replicas: #@ data.values.common.replicas
  #@ end
  selector:
    matchLabels:
      app: #@ service
      release: #@ data.values.app
  template:
    metadata:
      labels:
        app: #@ service
        release: #@ data.values.app
      annotations: #@ services[service]["annotations"]
#@ end
```

Command line output:
```
./ytt-linux-amd64 -f templates/deployment.yaml -f apps/values.yaml
ytt: Error: 
- key "annotations" not in dict
    in <toplevel>
      deployment.yaml:30 |       annotations: #@ services[service]["annotations"]

```

How can I access to annotations?

Thank you.
