### ISSUE TITLE
Using overlay to append an element to a list

### ISSUE THREAD

**Issue by larsks** [k14s/ytt#187]
I have a kubernetes deployment that for the purposes of this issue looks like this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: foo
          image: foo
```

I want to append another container to that document, so I've attempted the following:

```
#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({"kind": "Deployment"})
---
spec:
  template:
    spec:
      containers:
        - name: bar
          image: bar
```

But this fails with:

```
$ ytt -f example-deployment.yaml -f example-container.yaml
ytt: Error: Overlaying (in following order: example-container.yaml):
  Document on line example-container.yaml:3:
    Map item (key 'spec') on line example-container.yaml:4:
      Map item (key 'template') on line example-container.yaml:5:
        Map item (key 'spec') on line example-container.yaml:6:
          Map item (key 'containers') on line example-container.yaml:7:
            Array item on line example-container.yaml:8:
              Expected array item to have 'overlay/match' annotation
```

I'm not sure what the error message is trying to tell me, and I'm not sure I'm even attempting the match syntax correctly: examples in the docs are slim. I'm trying to say "take the contents of this document and merge it into the `containers` list in the source document".

Am I placing the `match` directive in the wrong place (e.g., should it be attached to the `containers` key somehow)?
