### ISSUE TITLE
Overlaying a yaml fragment

### ISSUE THREAD

**Issue by AndreSteenveld** [k14s/ytt#193]
Honestly I feel pretty foolish asking this as it seems so trivial. But I can't for the life of me figure out how to overlay a yaml-fragment from a function. I've seen a few similar issues which append to an array or use `template.replace` to put it in place.

As I'm pretty new to `ytt`  I'm not even sure if what I'm doing is idiomatic or even makes any sense at all. For a little background; I have a lot of docker-compose files which all get combined to either form a something that can be deployed using `docker-compose` or `docker stack`. Because these are all over the place I concatenate them and just send them to `stdin` (which would roughly look like the yaml in the gist). Depending on some provided flags the files containing the implementation of the function can be swapped out for another, providing the same API but different results, so because I don't exactly know the what file I'm loading just concatenating everything and providing it via `stdin` seems to make sense to me. 

Playground with gist: https://get-ytt.io/#gist:https://gist.github.com/AndreSteenveld/b4e25ad09653d3866ed3524718684134

**Comment by AndreSteenveld** [comment]
After sleeping on it for a night I realized I could add another document to the end of the file basically creating another entry in the stack of files. I did get this to work although it does seem rather verbose. Although the fact that the changes and how to do the overlay is fully encapsulated in to the fragment is nice it would be nicer to be able to apply without the overhead of concatenating an entire document.

https://get-ytt.io/#gist:https://gist.github.com/AndreSteenveld/bfef53333573adadb5b7544e5bef5a23

**Comment by AndreSteenveld** [comment]
Going through the issues again I did find #85 which seems to ask for a similar construct although in that case it could be resolved using `template.replace`.

Think about this some more, isn't it possible to refer to the current location in a document and apply an overlay from that point. Something like:

```yaml

#@ def fragment( ):
cheese: { }
bread:
  flatbread: { }
beverages:
  #@overlay/append
  - Coffee
  #@overlay/append
  - Tea
#@ end

---
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.all
#@overlay/match-child-defaults missing_ok=True
---

diet:
  food:
    #@ overlay.apply( self, fragment( ) )
    bread:
      waffle: { }
    dairy: { }
    beverages:
      - Water 
```

```yaml
#! What I would think the outcome would be:

diet:
  food:
    cheese: { }
    bread: 
      waffle: { }
      flatbread: { }
    dairy: { }
    beverages:
    - Water
    - Coffee
    - Tea

```

In #85 is was mentioned that it would be hard to decide what would be left and right. I think this can be largely be alleviated by being able to decide what the order is the overlays get applied in using the `apply` function. For the "inserting it back in to the tree" I would think that the tree is always left as that seems the intuitive thing to do, the fragment can specify overlay annotations to do any kind of non-default actions.

**Comment by AndreSteenveld** [comment]
Whittling this down a little more and in the vein of "just put another document on the stack" I've managed to get this down to a level where I think this would work well enough to get my work done.

Playground: https://get-ytt.io/#gist:https://gist.github.com/AndreSteenveld/bfef53333573adadb5b7544e5bef5a23

Also works with nested documents from functions: https://get-ytt.io/#gist:https://gist.github.com/AndreSteenveld/bfef53333573adadb5b7544e5bef5a23

**Comment by cppforlife** [comment]
> How do I overlay the fragment from beverages here? The following don't really work: ... #@ overlay.apply( beverages( ) ), this just seems to do nothing

overlay.apply takes two arguments: left side and right side. right side is the overlay. in this example, beverages() is the left side and there are no overlays to be applied so overlay.apply would just return it back.

> #! _: #@ template.replace( beverages( ) ), correctly throws an error about a duplicate key

that's right. because beverages key is already defined, ytt does not want by default to override it. template.replace is useful in similar cases, however, your example shows that it doesnt quite work for nested structures because it does not recursively merge (replaces top level matches: https://get-ytt.io/#gist:https://gist.github.com/cppforlife/8bc7e9fb2f537859116214e692bd7fba). for nested structures overlay.apply is better... (next bullet point)

> I've looked in the documentation and the tickets I could find but couldn't find anything... like overlay.insert( ... ), overlay.mixin( ... ) etc.

👍 great intuition for what to look for. it seems like you also found it a little later in the form of #85. ytt currently does not support "inline" overlays which is what you were trying to reach for to use to combine beverages value with result of beverages function return value.

> After sleeping on it for a night I realized I could add another document to the end of the file basically creating another entry in the stack of files.

assuming i understood this point, another way to add beverages to each service would be thru a separate overlay: line 39 and on in https://get-ytt.io/#gist:https://gist.github.com/cppforlife/5b3b913286051b0e3ce454025bc47766. this effectively skips the issue of using overlay functionality within an overlay itself vs. applying multiple overlays one after another.

> Think about this some more, isn't it possible to refer to the current location in a document and apply an overlay from that point. Something like:

yup, quite similar to what we were thinking about but havent implemented something like this (goes back to #85).

```yaml
diet:
  food:
    #@ overlay.apply( self, fragment( ) )
    bread:
      waffle: { }
```

though we would want to have self be already populated with inlined structure so that results of fragment() would be applied on top. may be something like this (done as annotation instead of plain code; dont think we would want to introduce a concept of `self`, especially in this case since it wouldnt be populated when overlay.apply in your example would run):

```yaml
diet:
  food:
    #@overlay/inline right=fragment( )
    bread:
      waffle: { }
```

> Playground: https://get-ytt.io/#gist:https://gist.github.com/AndreSteenveld/bfef53333573adadb5b7544e5bef5a23

yup, this is definitely an option. it seems you are using overlays to define some inheritance chain for how services are defined. and as you found out functions do work with wrapping documents.

we are not quite certain what kind of requirements you have for splitting overlays/config into separate files; however, one recommendation we commonly give is for your own configuration try plain templating, and rely on overlays for extra flexibility. example applied to your config:

- https://get-ytt.io#gist:https://gist.github.com/cppforlife/fad7d632eb7e12c0f3dc0b7097546f12 shows service function supporting "90%" of configuration via two variables, and then additional config "10%" could be added via overlay
- https://get-ytt.io/#gist:https://gist.github.com/cppforlife/1caa3e45d7b71ab7017cf40e8e084d72 - here is another flavor of how to structure it (which is pretty close to your last example)

(in the last example, it becomes pretty clear that it would have been convenient to avoid pulling out first and second functions and keeping them inline if we have ability to do "inline" overlays we talked about earlier).

thank you for providing gists in playground, it made things much clearer in terms of what you were trying to achieve.
