### ISSUE TITLE
yaml fragments are not indexable

### ISSUE THREAD

**Issue by mildred** [k14s/ytt#20]
This following example is failing with an error:

```yaml
#@ def some_data():
- "hello world"
#@ end
---
simple_key: #@ some_data()[0]
```

with the following error:
```
- unhandled index operation yamlfragment[int]
    config.yml:5 in <toplevel>
     L simple_key: #@ some_data()[0]
```

but it works with starlark literals:

```yaml
#@ def some_data():
#@   return ["hello world"]
#@ end
---
simple_key: #@ some_data()[0]
```

-------------------

Same for map indexing, this does not work:

```yaml
#@ def some_data():
hello: world
#@ end
---
simple_key: #@ some_data()["hello"]
```

with the following error:
```
- unhandled index operation yamlfragment[string]
    config.yml:5 in <toplevel>
     L simple_key: #@ some_data()["hello"]
```

but this works:

```yaml
#@ def some_data():
#@   return { "hello": "world" }
#@ end
---
simple_key: #@ some_data()["hello"]
```

**Comment by cppforlife** [comment]
we should probably add a method to yaml fragment to be able to convert it to plain types (like arrays and maps). eg

```yaml
#@ def some_data():
- "hello world"
#@ end
---
simple_key: #@ some_data().plain()          # returns ["hello world"]
simple_key2: #@ yaml.make(["hello world"])  # returns new yaml fragment from plain values
```

though not sure about naming of `plain()`.
