### ISSUE TITLE
Panic when overlaying a replaced node

### ISSUE THREAD

**Issue by cari-lynn** [k14s/ytt#201]
```
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")

#@ def annotation(key_value):
annotations:
  _: #@ template.replace(key_value)
#@ end

#@ def base():
annotations:
  some: value
#@ end

--- #@ template.replace([overlay.apply(base(), annotation({"key1": "val1", "key2": "val2"}))])
```
Creates a panic 

```
- runtime error: invalid memory address or nil pointer dereference (backtrace: goroutine 1 [running]:
    in <toplevel>
      template.yml:14 | --- #@ template.replace([overlay.apply(base(), annotation({"key1": "val1", "key2": "val2"}))])

    reason:
     runtime/debug.Stack(0x934960, 0x92dec0, 0xe82f20)
     	runtime/debug/stack.go:24 +0x9d
     github.com/k14s/ytt/pkg/template/core.ErrWrapper.func1.1(0xc00017cb78)
     	github.com/k14s/ytt@/pkg/template/core/errs.go:21 +0x9d
     panic(0x92dec0, 0xe82f20)
     	runtime/panic.go:679 +0x1b2
     github.com/k14s/ytt/pkg/filepos.(*Position).AsCompactString(0x0, 0xc000181680, 0x99cac0)
     	github.com/k14s/ytt@/pkg/filepos/position.go:47 +0x29
     github.com/k14s/ytt/pkg/filepos.(*Position).AsString(...)
     	github.com/k14s/ytt@/pkg/filepos/position.go:43
...
```
