### ISSUE TITLE
rfc: instrumenting Concourse pipeline job plans

### ISSUE THREAD

**Issue by abetaev** [k14s/ytt#204]
hi!

i am trying to build templates, which using overlay generate Concourse pipeline with a specific configuration. everything seems to be fine until i get to job plan which has arbitrary structure.

i am trying to find the most generic way to apply overlay onto same elements which may be in different nodes of YAML tree.

example:

    plan:
    - in_parallel:          
      - get: resourceA
        param1: value1A
        param2: value2
      - get: resourceB
    - task: test
      file: toolkit/tasks/mvn.task.yml
      params:
        args: test
      on_success:
        put: resourceC
        param1: value1C
      on_failure:
        ...

there are some other constructs, but general idea is the same.
each resource may have configuration which i want like to edit.

is it possible to do it so that plan structure would not matter?

thanks!

**Comment by gcheadle-vmware** [comment]
Hi @abetaev,

Thank you for reaching out! We would love to assist you with your issue; it would be helpful if you could provide an example showing your starting (base) config, as well as the desired final config. 

Once we have a more concrete understanding of what you would like to do, we can provide suggestions and examples to help solve your issue.

**Comment by abetaev** [comment]
yeah, sure. sorry for missing that obviously necessary part :)

`<additional-context>`
Concourse's pipeline YAML i want to instrument can be roughly split onto 2 sections:
```yaml

#! 1. resources
resources:
- name: project
  type: git
  source:
    uri: https://github.com/...
    branch: ((branch))

#! 2. jobs
jobs:
- name: deploy-project
  plan:
  - get: project
  - task: deploy
    file: project/ci/deploy.yml
    params:
      env: ((environment))
```
jobs may depend on resources. reference to resources is made via `get` and `put` elements which as any plan step may appear on different levels.
the final goal of this job is to deploy application to an environment.
job has `plan` node where it describes sequence of actions (one may say "algorithm") to be taken to achieve that. expressions like `((expr))` are substituted by Concourse from available property sources.
`</additional-context>`

jobs can have plan steps like `deploy` task on different levels of YAML structure.
```yaml
jobs:
- name: deploy-on-commit
  plan:
  - in_parallel:
    - get: project
      trigger: true #! triggers job whenever resource changes
    - get: ci
  - in_parallel:
    - task: deploy-to-env1
      file: ci/deploy.yml
      params:
        env: 'dev'
    - task: deploy-to-env2
      file: ci/deploy.yml
      params: ((env2-params))
        env: 'test'
      on_success:
        task: 'run integration tests against test'
        file: ci/integration-tests.yml
        params:
          env: 'test'

- name: test-dev-deployment
  plan:
  - task: 'run integration tests against dev'
    file: ci/integration-tests.yml
    params:
      env: 'dev'
```
i wanted use ytt to process doc from above into something like:
```yaml
jobs:
- name: deploy-project
  plan:
  - in_parallel:
    - get: project
    - get: ci
  - in_parallel:
    - task: deploy-to-env1
      file: ci/deploy.yml
      params:
        env: 'dev'
    - task: deploy-to-env2
      file: ci/deploy.yml
      params: ((env2-params))
        env: 'test'
      on_success:
        task: 'run integration tests against test'
        file: 'ci/integration-tests.yml'
        params:
          env: 'test'
          suite: 'feature-set-1' #! this is the first edit
        ensure:
          task: 'report'
          file: ci/report.yml

- name: test-dev-deployment
  plan:
  - task: 'run integration tests against dev'
    file: 'ci/integration-tests.yml'
    params:
      env: 'dev'
      suite: 'feature-set-1' #! this is the second edit
```

in other words, i want to select a node from arbitrary level of YAML structure by some criteria (here it's `has(task) and file == 'ci/integration-tests.yml'`) and apply an overlay on top of such node to add `suite: 'feature-set-1'`.

in some cases i would want to add or remove certain nodes into yaml structure.
e.g. in case job is operating with "dev" environment, i would like to remove "reporting" step to avoid clogging of reporting dashboard with intermediate development results, but when job is for "staging", i want additionally to push generated tag into VCS.

in some cases i would want to rename resources for multi-branch pipelines, so that all references in job plans (`get` and `put` steps) are renamed as well, and then combine all together to get a big YAML doc like this (compare to YAML from `additional-context`):
```yaml
resources:
- name: develop-project
  type: git
  source:
    uri: 'https://github.com/...'
    branch: develop
- name: release-project
  type: git
  source:
    uri: 'https://github.com/...'
    branch: master

jobs:
- name: develop-deploy-project
  plan:
  - get: project
  - task: deploy
    file: 'project/ci/deploy.yml'
    params:
      env: development

- name: release-deploy-project
  plan:
  - get: release-project
  - task: deploy
    file: 'project/ci/deploy.yml'
    params:
      env: staging
   - task: test
      file: project/ci/test.yml
      params:
        env: staging
    on_success:
      put: release-project
      params:
        tag: release-project/tag.txt #! generated during build
```

(please note, that examples are synthetic and may have logical issues)

thanks!

**Comment by pivotaljohn** [comment]
Thanks for the extra context, @abetaev! That makes it absolutely clear what you're asking...

Your question is about whether it is possible to apply an overlay on an arbitrary location in a YAML document.

That _is_ a challenge! I'm not sure it's possible, but I'm looking into it.

In the meantime, here are some thoughts. Perhaps we might find that you don't need overlays afterall?


## General thoughts about templating YAML:
- **Prefer templating over overlaying where you can**. When you can control/author your YAML, you're often better off templating than patching.
  - By "templating" I mean extracting values into data values and extracting YAML structure into functions.
  - The other way — patching your YAML using overlays — adds a level of indirection. This can be very expressive, but also easy to get wrong.
- **Keep it simple**. It's easy to make templates overly complicated, fast. We recommend using the simplest approach you can think of. Your future self will thank you.


## Templating Approach

If you _can_ author your pipeline config, here's a sketch:

```yaml
#@ load("@ytt:template", "template")

#@ def deploy(env,target):
task: #@ "deploy-to-{}".format(target)
file: ci/deploy.yml
params:
  env: #@ env
#@ end

#@ def integration_tests(env, suite, includeReport=False):
task: #@ "run integration tests against " + env
file: ci/integration-tests.yml
params:
  env: #@ env
  suite: #@ suite
#@ if/end includeReport:
ensure:
  task: "report"
  file: ci/report.yml
#@ end

---
jobs:
- name: deploy-on-commit
  plan:
  - in_parallel:
    - get: project
      trigger: true
    - get: ci
  - in_parallel:
    - #@ deploy("dev", "env1")
    - _: #@ template.replace(deploy("test", "env2"))
      on_success: #@ integration_tests("test", "feature-set-1", includeReport=True)
- name: test-dev-deployment
  plan:
  - #@ integration_tests(env="dev", suite="feature-set-1")
```

https://get-ytt.io/#gist:https://gist.github.com/pivotaljohn/cb280ff0cba5f945a25a778b2d7b89f3

- **Templatize from your target output and extract**. Start with the final pipeline config YAML and extract common logical chunks into functions.
- **each function captures a noun** (e.g. a step, or resource, or build log retention policy)
- **use `template.replace()` to mixin**
  - e.g. see `on_success` clause at `pipeline.yml:33`
- **prefer flag-controlled content over `template.replace()`**. It can be easy to get carried away with `template.replace()`. If an optional chunk always goes with 
  - e.g. see `ensure` clause at `pipeline.yml:16`


... again, sharing these thoughts in case this might adjust your thinking about approach.

We'll be back shortly with a definitive answer as to whether it's possible to overlay at an arbitrary node in the YAML tree.
