### ISSUE TITLE
make structs iterable

### ISSUE THREAD

**Issue by larsks** [k14s/ytt#205]
Let's allow maps to be used in `for` loops by iterating over the keys.

If I have a map defined:

```
#@data/values
---
mymap:
  key1: value1
  key2: value2
```

It would be conveninent to be able to do something like:

```
#@ load("@ytt:data", "data")
---
data:
  #@ for/end k in data.values.mymap:
  - name: #@ k
    value: #@ data.values.mymap[k]
```

The examples in https://github.com/k14s/ytt/commit/ead85c65ed47542199debc2ae974f4687a27179a featuring `struct.decode(...)` seem convoluted:

```
#@ load("@ytt:data", "data")
#@ load("@ytt:struct", "struct")
---
#@ mymap = struct.decode(data.values.mymap)
data:
  #@ for/end k in mymap:
  - name: #@ k
    value: #@ mymap[k]
```
