### ISSUE TITLE
Should `item.subkey` and `item["subkey"]` always be identical?

### ISSUE THREAD

**Issue by larsks** [k14s/ytt#206]
I have values that look like this:

```
#@data/values
---
simple_map:
  key1: foo
  key2: bar
nested_map:
  key1:
    subkey1: bar1
    subkey2: foo1
  key2:
    subkey1: bar1
    subkey2: foo1
```

In a template, I can refer to `data.values.simple_map.key1` and it Just Works. Given:

```
#@ load("@ytt:data", "data")
---
value: #@ data.values.simple_map.key1
```

I get:

```
value: foo
```

But when attempting to iterate over `nested_map`:

```
#@ load("@ytt:data", "data")
#@ load("@ytt:struct", "struct")
---
#@ mymap = struct.decode(data.values.mymap)
data:
  #@ for/end k in mymap:
  - name: #@ k
    value: #@ mymap[k].subkey1
```

I end up with the following failure:

```
ytt: Error:
- dict has no .subkey1 field or method
    in <toplevel>
      template.yml:8 |     value: #@ mymap[k].subkey1
```

Of course, that's ~~a dirty lie~~ misleading; and if we just change the syntax to use `var["key"]` instead of `var.key`:

```
#@ load("@ytt:data", "data")
#@ load("@ytt:struct", "struct")
---
#@ nested_map = struct.decode(data.values.nested_map)
data:
  #@ for/end k in nested_map:
  - name: #@ k
    value: #@ nested_map[k]["subkey1"]
```

It works as expected:

```
data:
- name: key1
  value: bar1
- name: key2
  value: bar1
```
