### ISSUE TITLE
Can I add a map to an array of maps?

### ISSUE THREAD

**Issue by amalagaura** [k14s/ytt#223]
I am not sure if this is supported and I am trying different overlay syntax. I am not really able to modify the source yamls so trying to do this with YTT.

```
---
id: 1
type: book
awards:
  books:
  - id: 1
    title: International Botev
    reviewers:
      - id: 2
        name: PersonB
  - id: 2
    title: Dayton Literary Peace Prize
    reviewers:
      - id: 3
        name: PersonC
        
#! How do I add a map to an array of maps?
```

```
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.all
---
awards:
  books:
    #@overlay/match by=overlay.all, expects="1+"
    #@overlay/match missing_ok=True
    reviewers:
      #@overlay/append
      - id: 1
        name: PersonA
 ```

So trying to add a map to the reviewers array in both books..

I created a StackOverflow ticket for it.
https://stackoverflow.com/questions/64504795/how-do-i-add-a-map-to-an-array-of-maps-in-ytt
