### ISSUE TITLE
Fix Broken Link for Schema Error

### ISSUE THREAD

**Issue by danielhelfand** [k14s/ytt#245]
Running `ytt` with `--enable-experiment-schema` with an invalid schema definition, such as below, returns the error underneath the invalid schema.

Invalid schema:
```
#@schema/definition data_values=True
---
vpc:
  name: ""
  subnet_ids:
  - 0
  #@schema/nullable
  subnet_config:
  - id: 0
    mask: "255.255.0.0"
    private: true
```

Error:
```
ytt: Error: Schema experiment flag was enabled but no schema document was provided. 
(See this propsal for details on how to include a schema document: https://github.com/k14s/design-docs/blob/develop/ytt/001-schemas/README.md#defining-a-schema-document)
```

When clicking on the link in the error to get more information, a 404 is returned.
