### ISSUE TITLE
[overlay] support a way to replace single collection item with multiple items (more specifically document in docset)

### ISSUE THREAD

**Issue by cppforlife** [k14s/ytt#251]
**Describe the problem/challenge you have**

given following yaml:

```
kind: List
items:
- kind: Bar
- kind: Foo
```

id like to get to this YAML

```
---
kind: Bar
---
kind: Foo
```

**Describe the solution you'd like**

not quite sure, but should be consistent in thinking about non-docset collections.

**Anything else you would like to add:**

currently `overlay/replace` supports arbitrary replacement of value of the node. when working with arrays one could in theory use it to modify anything about the array since it has access to the entire collection. for docsets that's not possible today since overlay/replace can only be placed on the document itself hence can only modify its own value, not its parent.

this also i think relates to being able to create new resources based existing resources. eg create a ServiceAccount per found Namespace. solution that we previously discussed was to add `overlay.modify__need_better_name(func)` where func would have access to entire docset, so would be able to do whatever it wants to do.

**Comment by gcheadle-vmware** [comment]
@joaopapereira and I attempted to tackle this problem and experienced the limitations that you described. However we are still confused about the use case. 

Does the `kind` key in the desired output yaml come from the `kind: List`, or from the array `items[*].kind`?

Is the goal to replace the yaml in the template file with the desired yaml, or to produce a new doc set from the template file? For example: given the following yaml:
```
kind: Deployment
metadata:
spec: 
  serviceAccountName: sa
```
is our desired out come this:
```
kind: Deployment
metadata:
spec: 
  serviceAccountName: sa
---
kind: ServiceAccount
metadata:
  name: sa
```
or this:
```
---
kind: ServiceAccount
metadata:
  name: sa
```
or something else?

**Comment by cppforlife** [comment]
> Does the kind key in the desired output yaml come from the kind: List, or from the array items[*].kind?

from the array items[*].kind. here is example without duplicate keys:

given following yaml:

```
---
items:
- kind: Bar
  metadata:
    name: bar
- kind: Foo
  metadata:
    name: foo
---
other: doc
```

id like to get to this YAML

```
---
kind: Bar
metadata:
  name: bar
---
kind: Foo
metadata:
  name: foo
---
other: doc
```

> Is the goal to replace the yaml in the template file with the desired yaml, or to produce a new doc set from the template file? For example: given the following yaml:

each yaml template has a docset already. so this is more about modification of that doc set. example shown above about service account could go either way -- it depends what ytt overlay code is written.

**Comment by joaopapereira** [comment]
Is it same to assume then that what we what as an overlay would be:
```
#@load("@ytt:docset", "docset")
---
#@docset/split
items:
- kind: Bar
  metadata:
    name: bar
- kind: Foo
  metadata:
    name: foo
---
other: doc
```

To convert into your expected result? Or where you thinking about some other option?
