### ISSUE TITLE
Merging two objects without overlay

### ISSUE THREAD

**Issue by maximeburri** [k14s/ytt#261]
Is it possible to merge an object (e.g. given by a function) with another one in the template without overlay ?

Example for this function:
```yaml
#@ def A_one_two():
A1: "one"
A2: "two"
#@ end
```

It is easy to define a list:
```yaml
list:
- #@ A_one_two()
- #@ A_one_two()
```

.. that outputs:
```yaml
list:
- A1: one
  A2: two
- A1: one
  A2: two
```

But how to add others keys by merging every objects without overlays ? Like:
```yaml
list:
  - A0: "0"
    A1: "one"
    A2: "two"
    A3: "3"
  - A0: "zero"
    A1: "one"
    A2: "two"
```

I expected that the following template would have given this result:
```yaml
list:
- A0: "0" 
  #@ A_one_two()
  A3: "3"
- A0: "zero" 
  #@ A_one_two()
```
... but it ignores functions (without warning) and outputs:
```yaml
list:
- A0: "0"
  A3: "3"
- A0: zero
```

Maybe it's not the philosophy of ytt?

Thanks for any help !

**Comment by cppforlife** [comment]
@maximeburri template.replace should work for your use case: https://get-ytt.io/#example:example-replace.

it's effectively a top level merge: https://github.com/vmware-tanzu/carvel.dev/blob/develop/content/ytt/docs/latest/lang-ref-ytt-template.md. for your example, it would look something like this:

```yaml
list:
- A0: "0" 
  _: #@ template.replace(A_one_two())
  A3: "3"
- A0: "zero" 
  _: #@ template.replace(A_one_two())
```

> ... but it ignores functions (without warning) and outputs:

this is because nothing is being done with the result of the function. (special case of this is `foo: #@ foo()` -- result of function is implied to be used as a value of foo map item because it's on the same line as foo key.) there is some more thinking to do for us to see if it's something we should error on (because nothing is being done with the function result).
