### ISSUE TITLE
[overlay] ability to match map item not just by key, but also by value

### ISSUE THREAD

**Issue by cppforlife** [k14s/ytt#27]
For example as part of linkerd installation I wanted to remove `strategy` and `status` fields on Deployments. To be more conservative we should probably allow value matching as well to avoid cases when key is being removed but it has an _unexpected_ value (in this example i expected values to be `{}`).

```
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Deployment"}),expects="1+"
---
spec:
  #@overlay/remove
  strategy: null
#@overlay/remove
status: null
```

**Comment by cppforlife** [comment]
possible via

```yaml
kind: Foo
spec:
  strategy: null
---
kind: Bar
spec:
  strategy: Blah
```

```yaml
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.all,expects="0+"
---
spec:
  #@overlay/match by=overlay.subset(None),expects="0+"
  #@overlay/remove
  strategy:
```
