### ISSUE TITLE
"on:" as keyword becomes "true:"

### ISSUE THREAD

**Issue by omgnuts** [k14s/ytt#275]
**What steps did you take:**
Using ytt data values to generate github actions templates, and the "on:" key becomes "true:".

```
[template.yml]
#@ load("@ytt:data", "data")
---
name: #@ data.values.action_name
on:
  push:
    branches: #@ data.values.action_branch
    paths: #@ data.values.action_paths
...
```

**What happened:**
The "on:" key was replaced by "true:"
```
[ytt-output]
name: Some name to publish
true: <------------------ expected on: instead of true:
  push:
    branches:
    - master
    paths:
    - .github/workflows/some-docker-image.yml
```

**What did you expect:**
Expected the "on:" key to remain 
```
[ytt-output]
name: Some name to publish
on: <------------------ expected on: as the correct output
  push:
    branches:
    - master
    paths:
    - .github/workflows/some-docker-image.yml
```

**Anything else you would like to add:**
I figure "on:" might be recognized as a boolean flag somewhere. So I tried "off:" as a keyword to test, and it became "false:" as well. Is there a way to tell ytt to preserve certain keywords as is? Eg.

In the meantime, I'm using sed to replace the piped output before generating the output files. 

```
"on":
```
to become 
```
on:
```

**Environment:**

- ytt version v0.31.0 release
- Windows 10
