### ISSUE TITLE
Schema supports floating types

### ISSUE THREAD

**Issue by pivotaljohn** [k14s/ytt#292]
Narrative:
**As a** configuration author
**I want** to denote a field in my schema as accepting non-whole numbers
**so that** consumers can provide reasonable values, and templates can depend on their existence.

---

## 🟢  Float checks as a float
**Given** I have a schema which includes a node whose value is a fractional number
**And** a data value which sets that node to a valid number
**When** I run `ytt` that includes that schema and data value
**Then** the resulting template value at that node comes from the data value 

```yaml
#! schema.yml
#@schema/match data_values=True
---
foo: 4.2
bar: 9.9
```

```yaml
#! dv.yml
#@data/values
---
foo: 13.0
bar: !!float 51
```

```yaml
#! template.yml
#@ load("@ytt:data", "data")
---
foo: #@ data.values.foo
bar: #@ data.values.bar
```

Then the result of `ytt -f schema.yml -f dv.yml -f template.yml --enable-experiment-schema` is:
```yaml
---
foo: 13.0
bar: 51
```

(without an error)

## 🟢  Integer checks as a Float

```yaml
#! schema.yml
#@schema/match data_values=True
---
foo: 4.2
```

```yaml
#! dv.yml
#@data/values
---
foo: 13
```

```yaml
#! template.yml
#@ load("@ytt:data", "data")
---
foo: #@ data.values.foo
```

Then the result of `ytt -f schema.yml -f dv.yml -f template.yml --enable-experiment-schema` is:
```yaml
---
foo: 13
```

(without an error)

## 🔴  Any non-number value fails to check as a Float

```yaml
#! schema.yml
#@schema/match data_values=True
---
foo: 4.2
bar: 9.9
```

```yaml
#! dv.yml
#@data/values
---
foo: "some string"
bar: []
```

Then the result of `ytt -f schema.yml -f dv.yml --enable-experiment-schema` is an error, with a message something like:

```
ytt: Error: Overlaying data values (in following order: dv.yml):
  Templating file 'dv.yml':
dv.yml:4 | foo: "some string"
         |
         | TYPE MISMATCH - the value of this item is not what schema expected:
         |      found: string
         |   expected: float (by schema.yml:4)

dv.yml:5 | bar: []
         |
         | TYPE MISMATCH - the value of this item is not what schema expected:
         |      found: array
         |   expected: float (by schema.yml:5)
```

## 📚 Documentation: Navigation
**Given** I want to learn how to mark a node in a schema as accepting any numeric value
**When** I navigate through `ytt`'s documentation
**Then** I intuitively find the reference that describes type inference and support for all numbers (not just ints)

## 🔍 Documentation: Search
**Given** I want to learn how to mark a node in a schema as accepting any numeric value
**When** I search for the most obvious search terms: "schema", "float", "number"
**Then** I see results that when I click on them take me to the most relevant reference.

---
**Implementation Notes**
On output, we may lose some type information because an integer is a valid float. (The starlark "type()" of `!!float 5` is float, but it would be output as `5` with type int).  This isn't a concern because floats are a strict superset of ints, so there shouldn't be anything that depends on having a decimal value.
