### ISSUE TITLE
Schema can be overlay'ed

### ISSUE THREAD

**Issue by pivotaljohn** [k14s/ytt#294]
**As a** Configuration Consumer
**I want** to augment the Schema
**so that** I can declare additional data values for use in my own templates/overlays

---

## 🟢  Additional Schema Appends to Root Library's Schema

**Given** there are two or more YAML documents annotated as `@schema/definition`
**When** I run `ytt` that includes those schema
**Then** the effective schema is the merge of those two

```yaml
#! schema-1.yml
#@schema/definition data_values=True
---
foo:
  bar: 3
```

```yaml
#! schema-2.yml
#@schema/definition data_values=True
---
foo:
  #@overlay/match missing_ok=True
  ree: ""
```

```console
$ ytt -f . --data-values-inspect
foo:
  bar: 3
  ree: ""
```

## 🟢  Additional Library-targeted Schema Appends to That Library's Schema

**Given** there is a private library with a YAML document annotated as `@schema/definition`
**And** a schema overlay (from the root library) targets that private library
**When** I run `ytt` that includes those schema
**Then** the effective schema in that library is the merge of those two

```console
.
├── _ytt_lib
│   └── libby
│       ├── schema.yml
│       └── template.yml
├── more-schema.yml
└── root.yml
```

```yaml
#! _ytt_lib/libby/template.yml
#@ load("@ytt:data", "data")
---
libby_data_values: #@ data.values
```

```yaml
#! _ytt_lib/libby/schema.yml
#@schema/definition data_values=True
---
foo:
  bar: 3
```

```yaml
#! more_schema.yml
#@library/ref "@libby"
#@schema/definition data_values=True
---
foo:
  #@overlay/match missing_ok=True
  ree: ""
```

```yaml
#! root.yml
#@ load("@ytt:library", "library")
#@ load("@ytt:template", "template")
#@ load("@ytt:data", "data")

--- #@ template.replace(library.get("libby").with_data_values({"ree": "set from root"}).eval())
---
root_data_values: #@ data.values
```

```console
$ ytt -f .
---
libby_data_values:
  foo:
    bar: 3
    ree: set from root
---
root_data_values: {}
```

## 🟢  Programmatically targeted Schema Appends to That Library's Schema

**Given** there is a private library with a YAML document annotated as `@schema/definition`
**And** the root library configures additional schema, programmatically
**When** I run `ytt` that includes those schema
**Then** the effective schema in that library is the merge of the original schema overlay'ed with the programmatically supplied overlay.

```console
├── _ytt_lib
│   └── libby
│       ├── schema.yml
│       └── template.yml
└── root.yml
```

```yaml
#! _ytt_lib/libby/template.yml
#@ load("@ytt:data", "data")
---
libby_data_values: #@ data.values
```

```yaml
#! _ytt_lib/libby/schema.yml
#@schema/definition data_values=True
---
foo:
  bar: 3
```

```yaml
#! root.yml
#@ load("@ytt:library", "library")
#@ load("@ytt:template", "template")
#@ load("@ytt:data", "data")

#@ def more_schema():
foo:
  #@overlay/match missing_ok=True
  ree: ""
#@ end

#@ libby = library.get("libby")
#@ libby = libby.with_schema(more_schema())
#@ libby = libby.with_data_values({"ree": "set from root"})

--- #@ template.replace(libby.eval())
---
root_data_values: #@ data.values
```

```console
$ ytt -f .
---
libby_data_values:
  foo:
    bar: 3
    ree: set from root
---
root_data_values: {}
```

## 🧗🏻‍♂️  Preventing Overlays from Breaking Schema's Contract

It is out-of-scope for _this_ story to detect and prevent contract-breaking changes in Schema.

For example, a Configuration Consumer _could_ include an overlay that removes a data value on which a template relies. That would result in a run-time error, the template complaining that this value is missing.

Some future story will enhance this process to help set proper guardrails while overlaying schema.
