### ISSUE TITLE
#@overlay/insert inserts out of order

### ISSUE THREAD

**Issue by StevenLocke** [k14s/ytt#308]
ℹ️ This bug should be addressed by implementing #371. See _that_ story for details.

Original Report 👇🏻 
---

**What steps did you take:**
Ran the following files through ytt:
```yaml
#! template.yaml

non-empty: doc
---
array:
- seeded
```

```yaml
#! overlay.yaml

#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.all, expects="1+"
---
#@overlay/match missing_ok=True
array:
#@overlay/append
- appended
#@overlay/match by=overlay.index(0)
#@overlay/insert before=True
- inserted before 0
```

**What happened:**
The command executed successfully, and output this yaml:
```yaml
non-empty: doc
array:
- appended
- inserted before 0
---
array:
- inserted before 0
- seeded
- appended
```

Note the order of the items in the array.  The "inserted before 0" item is added after the "appended" item in the first document, but (properly) before in the second.

**Anything else you would like to add:**
This doesn't occur if we insert an array key to the first doc
```yaml
non-empty: doc
array: []
```

which gets properly templated as:
```yaml
non-empty: doc
array:
- inserted before 0
- appended
```

**Environment:**

- ytt version (use `ytt --version`): This occurs on the playground at 0.30.0 as well as local dev at 0.31.0
- OS (e.g. from `/etc/os-release`): MacOS
