### ISSUE TITLE
Support for file-marks or rawOptions in App-spec for ytt

### ISSUE THREAD

**Issue by jmcclenny-PRE** [k14s/ytt#311]
**Describe the problem/challenge you have**
I have a need to utilize file-marks within the app-spec for kapp-controller.

**Describe the solution you'd like**
Would be nice to either have file-marks as a first class field or pass in via rawOptions
eg.
```yaml
template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        pathsFrom:
        - secretRef:
            name: secrets
      paths:
      - tkg-templates/providers/infrastructure-aws/v0.6.3/ytt
      - tkg-templates/providers/infrastructure-aws/ytt
      - tkg-templates/providers/ytt
      - tkg-templates/bom
      - tkg-templates/providers/config_default.yaml
      rawOptions: ["--file-mark 'bom**/*:type=text-plain'"]`
```
or possibly?

```yaml
template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        pathsFrom:
        - secretRef:
            name: secrets
      paths:
      - tkg-templates/providers/infrastructure-aws/v0.6.3/ytt
      - tkg-templates/providers/infrastructure-aws/ytt
      - tkg-templates/providers/ytt
      - tkg-templates/bom
      - tkg-templates/providers/config_default.yaml
      file-marks:
         text-plain: 
          - 'bom**/*
```
