### ISSUE TITLE
Change file content in configmap

### ISSUE THREAD

**Issue by Sly555** [k14s/ytt#320]
**Describe the problem/challenge you have**
I have a configmap used for storing configuration files for a tool. In each stages some values have to be different.
But the content is text in a yaml file ex : 

`configmap.yaml`
```yaml
#@ load("@ytt:data", "data")
apiVersion: v1
data:
  filter-grep.conf: | 
    # https://docs.fluentbit.io/manual/pipeline/filters/grep
    # Cette commande filtre les logs qui contienent NomTraitement
    # Ce filtre est le premier a passer et il est fait sur les donnees brutes
    [FILTER]
        name        grep
        match       **#@ data.values.match**
        exclude     log NomTraitement
  filter-kubernetes.conf: |
    [FILTER]
        Name             kubernetes
        Match            **#@ data.values.kubematch**
kind: ConfigMap
metadata:
  name: config
  namespace: **#@ data.values.nomprojet**
```

`Values.yaml`
```yaml
#@data/values
---
valeurs:
  nomprojet: test
  match: grep.*
  kubematch: kube.*
```

The #@ aren't recognized in this scenario. 

**Describe the solution you'd like**
Can it be possible to add a new set of chars that can indicate to ytt that it have to change the values ? Example #$ ($for string)
Or change the values in a textblock.

**Anything else you would like to add:**
New feature or existing one that can achieve this request.

Thanks.

![configmap](https://user-images.githubusercontent.com/77111210/110986075-388ce900-833b-11eb-8dde-cbb92067ca02.png)
