### ISSUE TITLE
Calling a yamlFragment by its string name

### ISSUE THREAD

**Issue by peterfeifanchen** [k14s/ytt#329]
I was wondering if I have:

```
load("config-5.lib.yml", "ingress")
```
Is it possible to call `ingress` using a string in my starlark file? For example
```
load("config-5.lib.yml", "ingress")

def function( fragmentString ):
   base = getattr([loaded module], fragmentString)
   return base()
```

**Comment by StevenLocke** [comment]
It is possible, though with a few tweaks! You're heading down the right path by getting the attribute from a loaded module and a parameter to the function, then calling it. I think your stumbling block may be getting that loaded module, and the accompanying `load` statement.

Similar to [this FAQ question](https://carvel.dev/ytt/docs/latest/faq/#can-i-load-multiple-functions-without-having-to-name-each-one) you can export multiple functions in a struct, and then load them together from that struct. That struct can then be used in your function definition to reach in and pull out a given function based on a name.

Here's an example:

```yaml
#! gress.lib.yaml

#@ load("@ytt:struct", "struct")

#@ def ingress():
#@   return "in"
#@ end

#@ def egress():
#@   return "out"
#@ end

#@ gress = struct.make(ingress=ingress, egress=egress)
```

```yaml
#! config.yaml

#@ load("gress.lib.yaml", "gress")

---
#@ def loadFromGress(functionName):
#@  base = getattr(gress, functionName)
#@  return base()
#@ end

ingress: #@ gress.ingress()
ingress_from_function: #@ loadFromGress("ingress")
egress: #@ gress.egress()
egress_from_function: #@ loadFromGress("egress")
```

Running `ytt -f config.yaml -f gress.lib.yaml` outputs:
```
ingress: in
ingress_from_function: in
egress: out
egress_from_function: out
```


-----------------


Alternatively, if you aren't able to change the libraries, you can make a struct in your config file, something like this:

```yaml
#! ingress.yaml

#@ def ingress():
#@   return "in"
#@ end
```

```yaml
#! egress.yaml

#@ def egress():
#@   return "out"
#@ end
```

```yaml
#! config.yaml

#@ load("@ytt:struct", "struct")
#@ load("ingress.lib.yml", "ingress")
#@ load("egress.lib.yml", "egress")

#@ gress = struct.make(ingress=ingress, egress=egress)

---
#@ def loadFromGress(functionName):
#@  base = getattr(gress, functionName)
#@  return base()
#@ end

ingress: #@ ingress()
ingress_from_function: #@ loadFromGress("ingress")
egress: #@ egress()
egress_from_function: #@ loadFromGress("egress")
```

And like before, running `ytt -f config.yaml -f ingress.lib.yaml -f egress.lib.yaml` outputs:
```
ingress: in
ingress_from_function: in
egress: out
egress_from_function: out
```
