### ISSUE TITLE
ytt silently skips yaml merge key

### ISSUE THREAD

**Issue by zhouhaibing089** [k14s/ytt#336]
**What steps did you take:**

merge key is described [here][1], however ytt silently ignores those special syntax.

**What happened:**

I have a yaml like below`foo.yaml`:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustertasks.tekton.dev
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    pipeline.tekton.dev/release: "v0.22.0"
    version: "v0.22.0"
spec:
  group: tekton.dev
  preserveUnknownFields: false
  versions:
    - &version
      name: v1alpha1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
    - !!merge <<: *version
      name: v1beta1
      storage: true
  names:
    kind: ClusterTask
    plural: clustertasks
    categories:
      - tekton
      - tekton-pipelines
  scope: Cluster
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: ["v1beta1"]
      clientConfig:
        service:
          name: tekton-pipelines-webhook
          namespace: tekton-pipelines
```

You can see `&version` and `!!merge <<: *version`. Then I run `ytt -f foo.yaml`, and no error reported, but the result YAML is incorrect:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustertasks.tekton.dev
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    pipeline.tekton.dev/release: v0.22.0
    version: v0.22.0
spec:
  group: tekton.dev
  preserveUnknownFields: false
  versions:
  - name: v1alpha1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
  - name: v1beta1
    storage: true
  names:
    kind: ClusterTask
    plural: clustertasks
    categories:
    - tekton
    - tekton-pipelines
  scope: Cluster
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions:
      - v1beta1
      clientConfig:
        service:
          name: tekton-pipelines-webhook
          namespace: tekton-pipelines
```

**What did you expect:**

I'd expect those merge key tags are preserved or expanded like below:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustertasks.tekton.dev
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    pipeline.tekton.dev/release: v0.22.0
    version: v0.22.0
spec:
  group: tekton.dev
  preserveUnknownFields: false
  versions:
  - name: v1alpha1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
  names:
    kind: ClusterTask
    plural: clustertasks
    categories:
    - tekton
    - tekton-pipelines
  scope: Cluster
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions:
      - v1beta1
      clientConfig:
        service:
          name: tekton-pipelines-webhook
          namespace: tekton-pipelines
```

**Anything else you would like to add:**

None.

**Environment:**

- ytt version (use `ytt --version`): ytt version 0.30.0
- OS (e.g. from `/etc/os-release`): osx

[1]: https://yaml.org/type/merge.html

**Comment by zhouhaibing089** [comment]
See https://github.com/tektoncd/pipeline/issues/3794 as well.

**Comment by gcheadle-vmware** [comment]
Hi @zhouhaibing089,

I see that the version of ytt that you are using is v0.30.0. If you take a peek at the [v0.31.0 release notes](https://github.com/vmware-tanzu/carvel-ytt/releases/tag/v0.31.0), you should see in that version we now support the merge operator. 
With your example, I made some slight canges to `foo.yml`:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustertasks.tekton.dev
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    pipeline.tekton.dev/release: "v0.22.0"
    version: "v0.22.0"
spec:
  group: tekton.dev
  preserveUnknownFields: false
  versions:
    - &version
      name: v1alpha1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
    -
      <<: *version
      #@yaml/map-key-override
      name: v1beta1
      #@yaml/map-key-override
      storage: true
(removed end of file for brevity...)
```
then running `ytt -f foo.yml`:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustertasks.tekton.dev
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    pipeline.tekton.dev/release: v0.22.0
    version: v0.22.0
spec:
  group: tekton.dev
  preserveUnknownFields: false
  versions:
  - name: v1alpha1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
  - served: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    name: v1beta1
    storage: true
(removed end of file for brevity...)
```

Let me know if this helps, and please feel free to reach out/respond if you have any further questions.
