### ISSUE TITLE
`(@` in a yaml string cause parser errors

### ISSUE THREAD

**Issue by scothis** [k14s/ytt#34]
ytt errors when parsing a string with the character sequence `(@`. I noticed this when trying to load a file that contained a JSON path expression.

```sh
$ echo 'JSONPath: .status.conditions[?(@.type=="Ready")].status' | ytt -f -
Error: Compiling YAML template 'stdin.yml': Missing code closing '@)' at line 1 col 46
```

**Comment by cppforlife** [comment]
currently ytt's text templating (`(@ ... @)`) conflicts with json path syntax. need to think about a way to avoid this situation. few options:

- change ytt text templating markers
- add a way to annotate yaml node to avoid text templating
- others...

**Comment by cppforlife** [comment]
for now one can use following methods to avoid this problem:

```yaml
JSONPath: #@ ".status.conditions[?(@.type==\"Succeeded\")].status"
```

or, if this is an upstream configuration file then it could just be considered to be plain yaml:

```bash
ytt -f config.yml --file-mark config.yml:type=yaml-plain
```

**Comment by mildred** [comment]
Would it be possible to hook into the YAML parser so unquoted strings would be templated with `(@`...`@)` and quoted strings would not. And is it possible to tag any quoted string with a special mark to force templating in it?

I'm thinking of:

```yaml
templated: (@= prefix @)-admin
untemplated: '.status.conditions[?(@.type=="Ready")].status'
force-templated: !t "http://(@= domain @)"
```

**Comment by cppforlife** [comment]
@mildred just saw your comment...

> Would it be possible to hook into the YAML parser so unquoted strings would be templated with (@...@) and quoted strings would not.

theoretically it's possible, but i dont quite like the distinction as both of those notations are strings. also given our general intent to be compatible with upstream yaml configurations, there would be no guarantee that someone will quote or not quote either of those cases.

> force-templated: !t "http://(@= domain @)"

i've been trying to avoid using yaml's builtin tags as they are effectively a "competing" solution to annotations (though less powerful). i dont think below is too far from what your force templated example shows:

```yaml
#@yaml/text-templated-strings
key_templated: "before (@= val1 @) middle (@= val2 @) after"
key_untemplated: "foo (@ somethign"
```
