### ISSUE TITLE
overlay/remove added key with null value

### ISSUE THREAD

**Issue by Birdrock** [k14s/ytt#343]
**What steps did you take:**
Modified the ytt playground [example-multiple-data-values](https://carvel.dev/ytt/#example:example-multiple-data-values) as follows:

config.yml
```
#! it can be useful to split data values
#! into multiple files, then combine them
#! before templating, for example,
#! to split default and production values

#@ load("@ytt:data", "data")

keys: #@ data.values.keys
names: #@ data.values.names
```

values-defaults.yml
```
#@data/values
---
names:
- default.example.com
```

values-production.yml
```
#@ load("@ytt:overlay", "overlay")
#@data/values
---
#@overlay/match missing_ok=True
keys:
  #@overlay/remove
  key1:
  key2: val2-new
  key3: val3
names:
#@overlay/match by=overlay.subset("default.example.com")
#@overlay/remove
-
- production.example.com
```

**What happened:**
```
keys:
  key1: null
  key2: val2-new
  key3: val3
names:
- production.example.com
```
`keys.key1` was inserted with a null value despite `#@overlay/remove`.

**What did you expect:**
```
keys:
  key2: val2-new
  key3: val3
names:
- production.example.com
```

**Environment:**

- ytt version (use `ytt --version`): `ytt version 0.31.0`
- OS (e.g. from `/etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by gcheadle-vmware** [comment]
Hi @Birdrock,

The [`#@overlay/remove` action](https://carvel.dev/ytt/docs/latest/lang-ref-ytt-overlay/#overlayremove) will match and remove the node on the left side (values-defaults.yml), based on the right side (values-production.yml). Since it looks like you deleted the `keys:` map and its children in values-defaults.yml, the `#@overlay/remove` action in your overlay will not match any nodes in values-defaults.yml, thus no action will be taken. If you want the result:
```
keys:
  key2: val2-new
  key3: val3
names:
- production.example.com
```
then you could simply delete the `#@overlay/remove ... key1:` from the values-production.yml.

Let me know if this makes sense to you; I'm happy to try and answer any further questions you have.
