### ISSUE TITLE
confusing error message when overlay/match expects is not quoted

### ISSUE THREAD

**Issue by dprotaso** [k14s/ytt#347]
```yaml
---
id: 1
type: book
modified: false
---
id: 2
type: book
modified: false
---
id: 3
type: course
modified: false
```

```yaml
#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.all, expects=1+
---
modified: true
```

Gives you the error message
```yaml
- got ')', want primary expression
    match-subset-docs.yml:2 | #@overlay/match by=overlay.all, expects=1+
```

What's confusing is that there isn't a `)` in the annotation that I wrote. 

I was hoping it would print an error saying my `expects` input should be quoted. Or ideally it accepts the `1+` as a valid token (ie. without the quoting)
