### ISSUE TITLE
when target for overlay is null - ytt errors out with confusing error message

### ISSUE THREAD

**Issue by dprotaso** [k14s/ytt#348]
```yaml
---
id: 1
annotations: null
---
id: 2
---
id: 3
```

overlay
```yaml
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.all, expects="1+"
---
#@overlay/match missing_ok=True
annotations:
  #@overlay/match missing_ok=True
  x: y
```

Error message is 
`
Overlaying (in following order: overlay.yml): Document on line overlay.yml:4: Map item (key 'annotations') on line overlay.yml:6: Expected map, but was <nil>
`

I'd prefer if the error message would highlight the _target_ value is null and print that file location instead of the overlay location.

Secondly, I wonder if a target `null` could be a special case where instead of `merge` it becomes a `replace`.
