### ISSUE TITLE
Removing liveness/readiness probes on a Kubernetes Deployment

### ISSUE THREAD

**Issue by damienleger** [k14s/ytt#354]
Hello,

I'm trying to remove only liveness/probes of a Kubernetes Deployment.

Pre-requisites: download metrics-server (https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml)

My overlay.yaml is the following
```
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind": "Deployment"})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by=overlay.index(0)
      - args:
        #@overlay/remove
        livenessProbe:
        #@overlay/remove
        readinessProbe:
```

The result is the following
```
$ diff -u components.yaml <(ytt -f components.yaml -f overlay.yaml)
--- components.yaml   2021-04-15 09:14:12.333101909 +0000
+++ /dev/fd/63  2021-04-15 09:37:35.707987758 +0000
@@ -128,32 +128,14 @@
         k8s-app: metrics-server
     spec:
       containers:
-      - args:
-        - --cert-dir=/tmp
-        - --secure-port=4443
-        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
-        - --kubelet-use-node-status-port
+      - args: null
         image: k8s.gcr.io/metrics-server/metrics-server:v0.4.2
         imagePullPolicy: IfNotPresent
-        livenessProbe:
-          failureThreshold: 3
-          httpGet:
-            path: /livez
-            port: https
-            scheme: HTTPS
-          periodSeconds: 10
         name: metrics-server
         ports:
         - containerPort: 4443
           name: https
           protocol: TCP
-        readinessProbe:
-          failureThreshold: 3
-          httpGet:
-            path: /readyz
-            port: https
-            scheme: HTTPS
-          periodSeconds: 10
         securityContext:
           readOnlyRootFilesystem: true
           runAsNonRoot: true
```

But as you can see it also remove "args" key. When I remove `#@overlay/match by=overlay.index(0)` ytt fails. Any ideas please?

N.B.: I know it's a really simple use case but I discovered ytt recently and I love it. The big issue for me is that the documentation really lacks "real life" use case such as this one when there is a multidoc yaml as input with a mixed of maps/array. The examples are always super simple.

**Comment by cari-lynn** [comment]
Hey @damienleger, really appreciate your feedback on the docs. We hope to improve this with some upcoming work to add guides so your feedback is really helpful. 

`containers` is a an array with a single array item, within that one array item, there are many keys, ie: `args` or `livenessProbe`.  We don't need to worry about `args` at all, even though it's the first key because order doesn't matter. 

If the keys you want to remove are only for a specific image, then it can be a good idea to match on the image name `name: metrics-server`. The overlay below will do that.

```
#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({"kind": "Deployment"})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by="name"
      - name: metrics-server
        #@overlay/remove
        livenessProbe:
        #@overlay/remove
        readinessProbe:
```

Alternatively, if you want to match on all images, regardless of name, you can do that via this overlay
```
#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({"kind": "Deployment"})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by=overlay.all, expects="1+"
      - 
        #@overlay/remove
        livenessProbe:
        #@overlay/remove
        readinessProbe:
```
The `- ` is indexing inside of the array item in `containers`.

Let me know if you need any more help tuning this.

**Comment by damienleger** [comment]
Thank you @cari-lynn it works perfectly! 🙂👌 
The trick of the `-` alone is what I needed to fix my overlay.index approach, but the matching on name is even better!

The fix using `#@overlay/match by=overlay.index(0)` for the records:
```
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind": "Deployment"})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by=overlay.index(0)
      -
        #@overlay/remove
        livenessProbe:
        #@overlay/remove
        readinessProbe:
```
