### ISSUE TITLE
[overlay] support a way to modify existing yaml node based on original node value (ie @overlay/modify)

### ISSUE THREAD

**Issue by cppforlife** [k14s/ytt#36]
there might be cases where instead of removing, merging or replacing it might be necessary to modify yaml node. one simple example might be:

```yaml
#@ def incr_by_2(val): return val + 2

spec:
  #@overlay/modify incr_by_2
  replicas:
```

to increment replicas by two in a particular environment. this assumes that base value is meaningful and relative values (or modification of base values in general) makes "business" sense.

@scothis brought another example where he was overlaying some data on top of knative manifests (https://github.com/knative/serving/blob/d7f29bd1a436bd651b2fa5ecf042ece6bf7cb09d/config/config-network.yaml#L105) and wanted to escape `{{` as they would not be compatible with helm (he was trying to create helm chart on the fly).
