### ISSUE TITLE
ytt does not intepret data-value "false" as false in if condition

### ISSUE THREAD

**Issue by StarpTech** [k14s/ytt#383]
**What steps did you take:**

```yml
spec:
  ingressClassName: "nginx-external"
  tls:
  - hosts:
    #@ wildcardHost = "*."  + data.values.domain
    - #@ wildcardHost if data.values.wildcardCert else data.values.subDomain + "." + data.values.domain
```

Everything is interpreted as `true`
```
ytt -v app=foo-1.0.0 -v imageTag=1.0.0 -v subDomain=foo -v domain=test.de -v wildcardCert=false -f ./k8s
ytt -v app=foo-1.0.0 -v imageTag=1.0.0 -v subDomain=foo -v domain=test.de -v wildcardCert=False -f ./k8s
ytt -v app=foo-1.0.0 -v imageTag=1.0.0 -v subDomain=foo -v domain=test.de -v wildcardCert=0-f ./k8s
```

**Environment:**

- ytt version (use `ytt --version`): 0.32.0
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
