### ISSUE TITLE
[HelpWanted] Cannot overlay file because of "ytt Error: undefined module overlay"

### ISSUE THREAD

**Issue by chenliu1993** [k14s/ytt#384]
**What steps did you take:**
I am using overlay module together with data-values to generate a yaml file. 
**What happened:**
ytt -f . showed 
`ytt: Error: 
- undefined: overlay`

And the problem part is this line:
`#@overlay/match by=overlay.subset({"kind":"DaemonSet"})`

Interestingly, I use the same content on ytt's playground and there is no issue.

**What did you expect:**
I expected the yaml could be generated.
**Environment:**

- MacOS with ytt  0.32.0
- CentOS with ytt 0.32.0

**Additions:**

Below are the debug infomation about `ytt -f .`

`### template
src:  tmpl: code: | srccode
????:    1: __ytt_tpl4_set_ctx_type("yaml") | 
????:    2: __ytt_tpl4_start_ctx("yaml") | 
????:    3: __ytt_tpl4_start_node(1) # *yamlmeta.DocumentSet | 
   1:    4: __ytt_tpl4_start_node(2) # *yamlmeta.Document | ﻿#@ load("@ytt:overlay", "overlay")
   1:    5: __ytt_tpl4_set_node(2) # *yamlmeta.Document | ﻿#@ load("@ytt:overlay", "overlay")
   2:    6: load("/values.star", "values") | #@ load("/values.star", "values")
   5:    7: __ytt_tpl4_start_node_annotation(3, "overlay/match", __ytt_tpl4_collect_node_annotation(by=overlay.subset({"kind":"DaemonSet"}))) # *yamlmeta.Document | #@overlay/match by=overlay.subset({"kind":"DaemonSet"})
   6:    8: __ytt_tpl4_start_node(3) # *yamlmeta.Document | ---
   6:    9: __ytt_tpl4_start_node(4) # *yamlmeta.Map | ---
   7:   10: __ytt_tpl4_start_node(5) # *yamlmeta.MapItem key=kind | kind: DaemonSet
   7:   11: __ytt_tpl4_set_node(5) # *yamlmeta.MapItem key=kind | kind: DaemonSet
   8:   12: __ytt_tpl4_start_node(6) # *yamlmeta.MapItem key=spec | spec:
   8:   13: __ytt_tpl4_start_node(7) # *yamlmeta.Map | spec:
   9:   14: __ytt_tpl4_start_node(8) # *yamlmeta.MapItem key=template |   template:
   9:   15: __ytt_tpl4_start_node(9) # *yamlmeta.Map |   template:
  10:   16: __ytt_tpl4_start_node(10) # *yamlmeta.MapItem key=spec |     spec:
  10:   17: __ytt_tpl4_start_node(11) # *yamlmeta.Map |     spec:
  11:   18: __ytt_tpl4_start_node(12) # *yamlmeta.MapItem key=containers |       containers:
  11:   19: __ytt_tpl4_start_node(13) # *yamlmeta.Array |       containers:
  12:   20: __ytt_tpl4_start_node_annotation(14, "overlay/match", __ytt_tpl4_collect_node_annotation(by=overlay.subset({"name": "kube-test"}))) # *yamlmeta.ArrayItem idx=? |       #@overlay/match by=overlay.subset({"name": "kube-test"})
  13:   21: __ytt_tpl4_start_node(14) # *yamlmeta.ArrayItem idx=? |       - image: #@ "{}/{}:{}".format(values.test.image.repository, values.test.image.path, values.test.image.tag)
  13:   22: __ytt_tpl4_start_node(15) # *yamlmeta.Map |       - image: #@ "{}/{}:{}".format(values.test.image.repository, values.test.image.path, values.test.image.tag)
  13:   23: __ytt_tpl4_start_node(16) # *yamlmeta.MapItem key=image |       - image: #@ "{}/{}:{}".format(values.test.image.repository, values.test.image.path, values.test.image.tag)
  13:   24: __ytt_tpl4_set_node(16, ("{}/{}:{}".format(values.test.image.repository, values.test.image.path, values.test.image.tag))) # *yamlmeta.MapItem key=image |       - image: #@ "{}/{}:{}".format(values.test.image.repository, values.test.image.path, values.test.image.tag)
????:   25: __ytt_tpl4_end_ctx(None) | total: 4.965424ms
ytt: Error: 
- undefined: overlay
    overlays/test_overlay.yaml:5 | #@overlay/match by=overlay.subset({"kind":"DaemonSet"})
- undefined: overlay
    overlays/test_overlay.yaml:12 |       #@overlay/match by=overlay.subset({"name": "kube-test"})`

**Comment by chenliu1993** [comment]
And there is already 
#@ load("@ytt:overlay", "overlay")

**Comment by cppforlife** [comment]
can you paste first 5-6 lines of your template?

**Comment by chenliu1993** [comment]
sure, here is the content:
**Base File**

```
apiVersion: apps/v1
kind: DaemonSet
spec:
  template:
    spec:
      containers:
      - name: kube-test
        image: test:stable
```

**Overlay File**

```
#@ load("@ytt:overlay", "overlay")
#@ load("/values.star", "values")


#@overlay/match by=overlay.subset({"kind":"DaemonSet"})
---
kind: DaemonSet
spec:
  template:
    spec:
      containers:
      #@overlay/match by=overlay.subset({"name": "kube-test"})
      - image: #@ "{}/{}:{}".format(values.test.image.repository, values.test.image.path, values.test.image.tag)
```
