### ISSUE TITLE
[website] figure out how to better explain ytt's strengths on the home page

### ISSUE THREAD

**Issue by cppforlife** [k14s/ytt#41]
based on @ctaymor's feedback i think we should find out better content that explains why someone should use ytt instead of erb/jinja/etc on the home page.

**Comment by brandonkal** [comment]
To that end, the main selling point I see in ytt is that you can start with plain YAML.
You could do that with jinja as well but it is less portable (python) and it is only text templating.

I would suggest placing this, or a similar loop, at the top  of the page above Features heading:
```yaml
array_with_data:
#@ for val in [1,5,{"key":"val"}]:
- item: #@ val
  kind: data
#@ end
```

I would also throw in a summarizing tagline such as "Data can be DRY too"
