### ISSUE TITLE
Working with values in yaml blocks

### ISSUE THREAD

**Issue by malcolm061990** [k14s/ytt#419]
Hi all!
Thank you for your perfect project :)
But I can't understand how to assign values from ytt data in yaml blocks.
Here what I have:
```
cat base.yaml # base.yaml content
#@data/values
---
FILEBEAT_ENVIRONMENT: develop
```

```
cat file1.yaml # file1.yaml content
#@ load("@ytt:data", "data")
---
data:
  env: #@ data.values.FILEBEAT_ENVIRONMENT
  filebeat.yml: |-
    filebeat.modules:
      - module: system
        environment: #@ data.values.FILEBEAT_ENVIRONMENT
```

Launched ytt:
```
ytt -f base.yaml -v FILEBEAT_ENVIRONMENT="qwer" -f file1.yaml # the result is below
data:
  env: qwer
  filebeat.yml: |-
    filebeat.modules:
      - module: system
        environment: #@ data.values.FILEBEAT_ENVIRONMENT
```

 I want to see `environment: qwer` instead of `environment: #@ data.values.FILEBEAT_ENVIRONMENT` but for some reason this value can't be parsed :(
Please, help
