### ISSUE TITLE
Nested array in a schema has a default value

### ISSUE THREAD

**Issue by cari-lynn** [k14s/ytt#424]
**What steps did you take:**

Given a schemas file that has an array item that is a map of at least two map items. One of those map items is a map, with the value of an array. 

Combined with a data values file that only provides one map item (essentially allowing the nested array's defaults to be filled in).

Using this schema:
```yaml
#@schema/match data_values=True
---
resources:
  - name: ""
    source:
      id:
        - I shouldn't show up
```
and this data values:
```yaml
#@data/values
---
resources:
  - name: ""
```
Run `ytt -f values.yml -f schema.yml --enable-experiment-schema --data-values-inspect`

**What happened:**
The default value for the array item 'I shouldn't show up' is populated
```yaml
resources:
- name: ""
  source:
    id:
    - I shouldn't show up
```
**What did you expect:**
The default value for an [array](https://carvel.dev/ytt/docs/latest/lang-ref-ytt-schema/#inferring-defaults-for-arrays) is an empty array.
```yaml
resources:
- name: ""
  source:
    id: []
```

**Anything else you would like to add:**

**Environment:**

- ytt version (use `ytt --version`): v0.34.0
- OS (e.g. from `/etc/os-release`):

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
