### ISSUE TITLE
Unable to merge data values into private library when they contain values not declared in the private library

### ISSUE THREAD

**Issue by blc1996** [k14s/ytt#429]
**What steps did you take:**
TLDR: The annotations like `#@overlay/append` `#@overlay/match-child-defaults missing_ok=True` are ignored when applying data values to ytt lib using
```
#@ def some_values():
#@   return data.values
#@ end

#@ --- #@ template.replace(some_lib.with_data_values(some_values()).eval())

```

The folder structure is like:
```
config
config/_ytt_lib
config/_ytt_lib/foo/templates/*
config/_ytt_lib/foo/values.yaml
config/foo.yaml
config/values.yaml
```
*config/foo.yaml*
```
#@ load("@ytt:data", "data")
#@ load("@ytt:library", "library")
#@ load("@ytt:template", "template")

#@ some_lib = library.get("foo")

#@ def some_values():
#@   return data.values
#@ end

--- #@ template.replace(some_lib.with_data_values(some_values()).eval())

```

*config/_ytt_lib/foo/values.yaml*
```
#@data/values
#@overlay/match-child-defaults missing_ok=True

---
foo:
    tolerations: []

```

*config/values.yaml*
```
#@data/values
#@overlay/match-child-defaults missing_ok=True
---
foo:
    tolerations:
    #@overlay/append
    - key: CriticalAddonsOnly
      operator: Exists
    #@overlay/append
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
```

**What happened:**
When using ytt
`ytt --ignore-unknown-comments -f config`

Got the following error
```
$ ytt --ignore-unknown-comments -f config
ytt: Error: 
- library.eval: Evaluating library 'addons/packages/addons-manager/bundle/config': Overlaying data values (in following order: _ytt_lib/addons/packages/addons-manager/bundle/config/values.yaml, additional data values): Overlaying additional data values on top of data values from files (marked as @data/values): Document on line ?: Map item (key 'foo') on line ?: Map item (key 'tolerations') on line ?: Array item on line ?: Expected array item to have 'overlay/match' annotation
    in <toplevel>
      addons-manager.yaml:11 | --- #@ template.replace(addons_manager_lib.with_data_values(addons_manager_values()).eval())
```

**What did you expect:**
The template rendering should finish successfully. The annotations in values.yaml outside the ytt lib should not be ignored.

**Anything else you would like to add:**
If I do
*config/foo.yaml*
```
#@ load("@ytt:data", "data")
#@ load("@ytt:library", "library")
#@ load("@ytt:template", "template")

#@ some_lib = library.get("foo")

#@ def some_values():
foo:
    tolerations:
    #@overlay/append
    - key: CriticalAddonsOnly
      operator: Exists
    #@overlay/append
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
#@ end

--- #@ template.replace(some_lib.with_data_values(some_values()).eval())

```

The template renders without issue

**Environment:**

- ytt version (use `ytt --version`):
- OS (e.g. from `/etc/os-release`):

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
