### ISSUE TITLE
long string values are split into multiple lines

### ISSUE THREAD

**Issue by rkatti** [k14s/ytt#45]
```
  podAnnotations:
#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({})
---
env:
  #@overlay/match missing_ok=True
  JAVA_OPTS: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaajjjj jjjjjjjjjjjjjjjjjjjjj jjjjjjjjjjjjjjjjjjjjjjjjjj  jjjjjjjjjj  jjjjj'


kubernetes:
  #@overlay/remove
  volumes:


--------------

Produces : 


env:
  JAVA_OPTS: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaajjjj jjjjjjjjjjjjjjjjjjjjj
    jjjjjjjjjjjjjjjjjjjjjjjjjj jjjjjjjjjj jjjjj
kubernetes:
  podAnnotations:
    prometheus.io/scrape: true
    prometheus.io/port: 8008
    prometheus.io/path: prometheus_metrics



We see that JAVA_OPTS value is split across multiple lines. Now if I eliminate the spaces, it does preserve the line. Here is overlay with no spaces : 


env:
  JAVA_OPTS: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
kubernetes:
  podAnnotations:
    prometheus.io/scrape: true
    prometheus.io/port: 8008
    prometheus.io/path: prometheus_metrics

```

**Comment by cppforlife** [comment]
line splitting appears to be yaml.v2 library behaviour; however, it's still a correct yaml. can be seen here:

with this input:

```yaml
env:
  JAVA_OPTS: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaajjjj jjjjjjjjjjjjjjjjjjjjj
    jjjjjjjjjjjjjjjjjjjjjjjjjj  jjjjjjjjjj  jjjjj
```

it still interprets it as wanted:

```
$ pbpaste |ytt -f- --output-type json
{"env":{"JAVA_OPTS":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaajjjj jjjjjjjjjjjjjjjjjjjjj jjjjjjjjjjjjjjjjjjjjjjjjjj  jjjjjjjjjj  jjjjj"}}
```

is there a particular concern you have about this behaviour?
