### ISSUE TITLE
Is it possible to do string interpolation in YTT?

### ISSUE THREAD

**Issue by alexander-bruun** [k14s/ytt#467]
Is it possible to do string interpolation in YTT?

Something along the lines of this.

config.yml:
```
#@ load("@ytt:data", "data")

---
test: #@ data.values.map["data.values.var"].somekey
```

schema.yml:
```
#@data/values-schema
---
var: "bar"

map:
  foo:
    somekey: 123abc
  bar: 
    somekey: abc123
```

expected result:
```
---
test: abc123
```

I couldn't find such a example in the playground, so wanted to inquire here if this is possible somehow.
