### ISSUE TITLE
deep merge for data values

### ISSUE THREAD

**Issue by sbvitok** [k14s/ytt#479]
Hi!
Can you help me to understand, how to create schema for map where keys can be random and located in separate data/values files ?

For example I have 3 data/values file

file1.yaml
```
#@data/values
---
labels:
 label1: one
 label2: two
 label3: three
```

file2.yaml
```
#@data/values
---
labels:
  label2: four
  label4: four
```

file3.yaml
```
#@data/values
---
annotations:
  name: five
labels:
  label3: five
```

how to make ytt to load this files?

**Comment by cppforlife** [comment]
these 2 documents should be of help:
- https://carvel.dev/ytt/docs/latest/ytt-data-values/
- https://carvel.dev/ytt/docs/latest/how-to-use-data-values/

when using #@data/values means of specifying values, they are merged via ytt overlay mechanism. first data values configuration acts as a base and all following values are merged on top. see this as an example: https://carvel.dev/ytt/docs/latest/ytt-data-values/#splitting-data-values-overlays-into-multiple-files

if your question was about defining @data/values-schema with maps that have arbitrary keys, then currently the only way to support it is via any=True
 
```
#@data/values-schema
---
#@schema/type any=True
labels: {}
```

and you would fill it out with

```
#@data/values
---
labels:
  #@overlay/match missing_ok=True
  foo: blah
```

or via --data-values-file foo.yml where foo.yml contains

```
labels:
  foo: bar
```

**Comment by sbvitok** [comment]
@cppforlife thx for you answer!
```
#@overlay/match-child-defaults missing_ok=True
```
This is what I was looking for!

schema.yaml
```
#@data/values-schema
---
#@schema/type any=True
labels: {}

#@schema/type any=True
annotations: {}
```

file1.yaml
```
#@data/values
#@overlay/match-child-defaults missing_ok=True
---
labels:
 label1: one
 label2: two
 label3: three
```

file2.yaml
```
#@data/values
#@overlay/match-child-defaults missing_ok=True
---
labels:
  label2: four
  label4: four
```

file3.yaml
```
#@data/values
#@overlay/match-child-defaults missing_ok=True
---
annotations:
  name: five
labels:
  label3: five
```

In this configuration deep merge works perfectly! Thx!
