### ISSUE TITLE
loading data in data/values 

### ISSUE THREAD

**Issue by mhoshi-vm** [k14s/ytt#485]
I am trying to do something like the following.

```
#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@data/values
---
registry:
  username: #@ data.values.tanzunet_username
  password: #@ data.values.tanzunet_password
```

Of course I have another data yaml file that defines `data.values.tanzunet_username` but i fail with the following.

```
  Templating file 'acc-data-values.yaml':
- struct has no .tanzunet_username field or method
    in <toplevel>
      acc-data-values.yaml:9 |   username: #@ data.values.tanzunet_username
```

I am guessing you cannot `load("@ytt:data", "data")` in a data file, but is this correct and is there any workaround ?
