### ISSUE TITLE
Unexpected behavior for key named 'on'

### ISSUE THREAD

**Issue by DennisDenuto** [k14s/ytt#487]
**What steps did you take:**
I was trying to create a template for a github action:

```yaml
on:
  push:
    branches:
      - develop
```

**What happened:**
ytt -f github-action.yml

results in:
```yaml
true:
  push:
    branches:
    - develop
```

**What did you expect:**
For the key 'on' to stay as 'on' and not change to 'true'

**Environment:**

- ytt version (use `ytt --version`): ytt version 0.36.0
- OS (e.g. from `/etc/os-release`): osx

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
