### ISSUE TITLE
Add function to escape url query parameters

### ISSUE THREAD

**Issue by swenzel** [k14s/ytt#52]
It would come in very handy to be able to call a function for url encoding strings.

Use Case:
A liveness probe queries a rest endpoint which requires a parameter that contains speical characters.

Example:
```
#@load("@ytt:url", "url")

livenessProbe:
    httpGet:
        path: #@ "/query?param={}".format(url.escape("I'm URL encoded!"))
```
*Of course exact naming doesn't matter.*

Should result in
```
livenessProbe:
    httpGet:
        path: "/query?param=I%27m%20URL%20encoded%21"
```
