### ISSUE TITLE
`@schema/...` annotations within a subtree annotated `@schema/type any=True` should be invalid

### ISSUE THREAD

**Issue by pivotaljohn** [k14s/ytt#522]
_(Inspired by #515)_

Today, when an author marks their schema with "any type", they can also include `@schema/...` annotations within, without error.

For example:
```yaml
#@data/values-schema                                                            
                                                                                
---                                                                             
#@schema/type any=True                                                                                           
spec:                                                                           
  #@schema/type any=False                                                       
  staticPasswords:                                                              
  - username: ""                                                                
    email: ""                                                                   
    hash: ""                                                                    
    userID: ""
```

This can surprise users when such annotations have no effect (e.g. the user was hoping to see their array items defaulted within `spec.staticPasswords`).

Let's be explicit and clear that such annotations are not allowed by reporting error whenever any `@schema/...` annotation is found within a "any type" annotation.
For example, the above schema should result in an error:

```
Invalid schema
==============
@schema/... are not allowed within a fragment annotated `@schema/type any=True`

schema.yml:
    |
  6 |   #@schema/type any=False
  7 |   staticPasswords:
    |

    = found: @schema/type annotation
    = expected: no @schema/... annotations within "any type" fragment
```
_(note that this error message format presumes work scoped in #521 is complete)_

---

edit: add case where `@schema/default` is on the same node as `@schema/type any=True`
