### ISSUE TITLE
OpenAPI keys are in a uniform order

### ISSUE THREAD

**Issue by cari-lynn** [k14s/ytt#551]
# Why
When keys that take multiple lines are listed prior to keys that are only one line, it can be difficult to visually parse which indentation level corresponds to which key. 

# Current Behavior
## Some keys appear in different order than others
From this data values schema:
```yaml
#@data/values-schema
#@schema/desc "Network configuration values"
---
#@schema/desc "List of database connections"
db_conn:
#@schema/desc "A network entry"
- 
  #@schema/desc "The hostname"
  hostname: ""
  #@schema/desc "Port should be between 49152 through 65535"
  port: 0
  #@schema/desc "Timeout in minutes"
  timeout: 1.0
  #@schema/desc "Any type is allowed"
  #@schema/type any=True
  any_key: thing
  #@schema/desc "When not provided, the default is null"
  #@schema/nullable
  null_key: ""
```
`ytt -f . --data-values-schema-inspect -o openapi-v3`
the result is:
```yaml
type: object
additionalProperties: false
description: Network configuration values
properties:
   db_conn:
     type: array
     description: List of database connections
     items:
       type: object
       additionalProperties: false
       description: A network entry
       properties:
          hostname:
            type: string
            default: ""
            description: The hostname
         port:
           type: integer
           default: 0
           description: Port should be between 49152 through 65535
         timeout:
           type: number
           default: 1
           format: float
           description: Timeout in minutes
         any_key:
           nullable: true                             # <- Nullable first here
           default: thing
           description: Any type is allowed
         null_key:
           type: string
           default: null
           nullable: true                             # <- nullable third here
           description: When not provided, the default is null
     default: []
```

Desired behavior:
* `default` last
* `description` second to last
* `format` after `type`
* keys are in consistent order 
```yaml
type: object
additionalProperties: false
description: Network configuration values
properties:
   db_conn:
     type: array
     description: List of database connections
     items:
       type: object
       additionalProperties: false
       description: A network entry
       properties:
          hostname:
            type: string
            description: The hostname
            default: ""
         port:
           type: integer
           description: Port should be between 49152 through 65535
           default: 0
         timeout:
           type: number
           format: float
           description: Timeout in minutes
           default: 1
         any_key:
           nullable: true
           description: Any type is allowed
           default: thing
         null_key:
           type: string
           nullable: true
           description: When not provided, the default is null
           default: null
     default: []
```
