### ISSUE TITLE
Annotation to allow text templating for entire doc

### ISSUE THREAD

**Issue by h4xnoodle** [k14s/ytt#58]
As of 0.17.0, text templating requires the annotation for all parent nodes.

An example where there is tedious is the construction of concourse pipelines: we use loops to design the jobs, and each job uses text templating (i.e. fill in a release name to build). Upgrading from prior to 0.17.0 to latest as of this writing requires the annotation in many places for us.

Would it be possible to have a CLI option or doc-wide annotation to enable? Is there a perceived/real performance cost to this?

**Comment by nimakaviani** [comment]
I am curious to see an example of how you use text templating in concourse pipelines. I would assume in a yaml document, python should give you enough tools and constructs not to require text templating, but maybe I am missing something in your design.

Can you provide an example? thanks!

**Comment by h4xnoodle** [comment]
The pipeline is the Bosh stemcells publisher, and so it enumerates through all the released stemcells, LTS stemcells, all builds. It's large. We use loops and functions to define common blocks. Within the functions there are string templates, which read from the data loaded.

`data` contains arrays of stemcell versions/names
```
#@data/values
---
oss:
- os: ubuntu-xenial
  version: 456
  os_name: ubuntu
  os_version: xenial
  build_aws: true
- os: ubuntu-xenial
  version: 315
  os_name: ubuntu
  os_version: xenial
  build_aws: true
- os: ubuntu-xenial
  version: 250
  os_name: ubuntu
  os_version: xenial
  build_aws: true
- os: ubuntu-xenial
  version: 170
  os_name: ubuntu
  os_version: xenial
  build_aws: true
- os: ubuntu-xenial
  version: 97
  os_name: ubuntu
  os_version: xenial
  build_aws: true
- os: centos-7
  version: 3763
  os_name: centos
  os_version: 7
  build_aws: false
```

Below is a snippet from the whole file. I'm sure there is a way to have _less_ of the new annotations, but it still was developer effort to sprinkle them in.

From your comment it sounds like there might be a better pattern to adhere to when designing these large yaml files. Do you have any recommendations?

```
#@ load("@ytt:data", "data")

#@ def build_light_aws_stemcell_new(name, lts, stemcell_os, stemcell_version, builder_src, input_stemcell, output_stemcell, prefix, region, bucket_prefix, tag, ami_destinations):
do:
- #@ get_aws_light_stemcells(input_stemcell, lts, stemcell_os, stemcell_version, builder_src, tag)
- #@ build_light_aws_stemcell(name, builder_src, input_stemcell, output_stemcell, prefix, region, bucket_prefix, tag, ami_destinations)
#@ end

---
#@ def build_light_aws_stemcell(name, builder_src, input_stemcell, output_stemcell, prefix, region, bucket_prefix, tag, ami_destinations):
file: bosh-stemcells-ci/tasks/light-aws/build.yml
task: #@ name
#@yaml/text-templated-strings
input_mapping:
  builder-src: (@= builder_src @)
  input-stemcell: (@= input_stemcell @)
#@yaml/text-templated-strings
output_mapping:
  light-stemcell: (@= output_stemcell @)
#@yaml/text-templated-strings
params:
  ami_access_key: ((publish__(@= prefix @)_access_key))
  ami_bucket_name: ((publish__(@= bucket_prefix @)_bucket))
  ami_description: ((publish__ami_description))
  #@ if ami_destinations != "":
  ami_destinations: (@= ami_destinations @)
  #@ end
  ami_encrypted: ((publish__ami_encrypted))
  ami_kms_key_id: ((publish__ami_kms_key_id))
  ami_region: ((publish__(@= region @)_region))
  ami_secret_key: ((publish__(@= prefix @)_secret_key))
  ami_server_side_encryption: ((publish__(@= prefix @)_server_side_encryption))
  ami_virtualization_type: hvm
  ami_visibility: ((publish__ami_visibility))
  #@ if tag != "":
tags:
- #@ tag
  #@ end
#@ end

#@ def get_aws_light_stemcells(input_stemcell, lts, stemcell_os, stemcell_version, builder_src, tag):
#@yaml/text-templated-strings
in_parallel:
- get: (@= input_stemcell @)
  params:
    include_files:
    - bosh-stemcell-*-aws-xen-hvm-(@= stemcell_os @)-go_agent.tgz
  resource: candidate-(@= stemcell_os @)-stemcell-(@= stemcell_version @)(@= lts @)
  trigger: true
  version: every
  #@ if tag != "":
  tags:
  - #@ tag
  #@ end
- get: (@= builder_src @)
  passed:
  - test-aws-unit
  - test-aws-integration
  - test-aws-drivers
  resource: light-aws-builder-src
  #@ if tag != "":
  tags:
  - #@ tag
  #@ end
#@ end

---
#@yaml/text-templated-strings
groups:
- name: all
  jobs:
  - test-aws-unit
  - test-aws-drivers
  - test-aws-integration
  - concourse-alignment
  #@ for stemcell in data.values.oss:
    #@ if stemcell.build_aws:
  - build-light-aws-(@= stemcell.os @)-(@= str(stemcell.version) @)
    #@ end
  - build-light-google-(@= stemcell.os @)-(@= str(stemcell.version) @)
  - publish-(@= stemcell.os @)-(@= str(stemcell.version) @)
  #@ end

  #@ for stemcell in data.values.lts:
  - build-light-aws-(@= stemcell.os @)-(@= str(stemcell.version) @)
  - build-light-google-(@= stemcell.os @)-(@= str(stemcell.version) @)
  - publish-(@= stemcell.os @)-(@= str(stemcell.version) @)
  #@ end
- name: oss
  jobs:
  #@ for stemcell in data.values.oss:
    #@ if stemcell.build_aws:
  - build-light-aws-(@= stemcell.os @)-(@= str(stemcell.version) @)
    #@ end
  - build-light-google-(@= stemcell.os @)-(@= str(stemcell.version) @)
  - publish-(@= stemcell.os @)-(@= str(stemcell.version) @)
  #@ end
- name: lts
  jobs:
  #@ for stemcell in data.values.lts:
  - build-light-aws-(@= stemcell.os @)-(@= str(stemcell.version) @)
  - build-light-google-(@= stemcell.os @)-(@= str(stemcell.version) @)
  - publish-(@= stemcell.os @)-(@= str(stemcell.version) @)
  #@ end
#@ for stemcell in data.values.oss:
- name: (@= stemcell.os @)/(@= str(stemcell.version) @)
  jobs:
  #@ if stemcell.build_aws:
  - build-light-aws-(@= stemcell.os @)-(@= str(stemcell.version) @)
  #@ end
  - build-light-google-(@= stemcell.os @)-(@= str(stemcell.version) @)
  - publish-(@= stemcell.os @)-(@= str(stemcell.version) @)
#@ end
#@ for stemcell in data.values.lts:
- name: (@= stemcell.os @)/(@= str(stemcell.version) @)
  jobs:
  - build-light-aws-(@= stemcell.os @)-(@= str(stemcell.version) @)
  - build-light-google-(@= stemcell.os @)-(@= str(stemcell.version) @)
  - publish-(@= stemcell.os @)-(@= str(stemcell.version) @)
#@ end

#@yaml/text-templated-strings
jobs:
- name: test-aws-unit
....
```

**Comment by nimakaviani** [comment]
ok so like I said you can easily use python to replace the text templating that you are doing and get rid of text templating all together. In fact that may make your templates more readable too. I converted a tiny bit of your template to give you an idea. see below:

old code:
```groups:
- name: oss
  jobs:
  #@ for stemcell in data.values.oss:
    #@ if stemcell.build_aws:
  - build-light-aws-(@= stemcell.os @)-(@= str(stemcell.version) @)
    #@ end
  - build-light-google-(@= stemcell.os @)-(@= str(stemcell.version) @)
  - publish-(@= stemcell.os @)-(@= str(stemcell.version) @)
```
new code:
```groups:
- name: oss
  jobs:
  #@ for stemcell in data.values.oss:
  #@ if/end stemcell.build_aws:
  - #@ "build-light-aws-{}-{}".format(stemcell.os, str(stemcell.version))
  - #@ "build-light-google-{}-{}".format(stemcell.os, str(stemcell.version))
  - #@ "publish-{}-{}".format(stemcell.os,str(stemcell.version))
  #@ end
```

**Comment by cppforlife** [comment]
you can already throw in that annotation on top of yaml doc (`---`). there is no way today to apply it to multiple yaml docs though.

**Comment by cppforlife** [comment]
the reason why we introduced it as an annotation recently is because `(@` was erroneously interpreted as ytt syntax in some cases even though it wasnt (it was actually json path syntax within k8s crd definitions).

i dont think we would want to introduce this as a cli flag since its content specific and user of ytt isnt necessarily aware of all templating going on; however, i would be curious to know if my above comment is enough to declutter its use.

**Comment by h4xnoodle** [comment]
from @cppforlife's comment for top of doc: this worked.

What I had done before was add right after data load (did not work):
```
#@ load("@ytt:data", "data")
#@yaml/text-templated-strings

#@ def build_light_aws_stemcell_new(name, lts, stemcell_os, stemcell_version, builder_src, input_stemcell, output_stemcell, prefix, region, bucket_prefix, tag, ami_destinations):
do:
- #@ get_aws_light_stemcells(input_stemcell, lts, stemcell_os, stemcell_version, builder_src, tag)
- #@ build_light_aws_stemcell(name, builder_src, input_stemcell, output_stemcell, prefix, region, bucket_prefix, tag, ami_destinations)
#@ end

---
...
```
correcting to 
```
#@ load("@ytt:data", "data")

#@ def build_light_aws_stemcell_new(name, lts, stemcell_os, stemcell_version, builder_src, input_stemcell, output_stemcell, prefix, region, bucket_prefix, tag, ami_destinations):
...
#@end

#@yaml/text-templated-strings
---
```
works. It really needs to be _right_ at the top of the doc. Thanks @cppforlife & @nimakaviani

**Comment by jessehu** [comment]
Hi @cppforlife , I have a yaml file which contains multi yaml docs '---':

```
---
kind: Secret
metadata:
  labels:
    app: (@= data.values.myapp @)-app

---
kind: ConfigMap
metadata:
  labels:
    app: (@= data.values.myapp @)-app

---
kind: Deployment
metadata:
  labels:
    app: (@= data.values.myapp @)-app
```
Instead of adding `#@yaml/text-templated-strings` before all '---' lines, can we make  `#@yaml/text-templated-strings` the default behaviour? Or a ytt commant line option for it? Or just one `#@yaml/text-templated-strings` at the beginning applies to all '---' in a single yaml file?

Since adding `#@yaml/text-templated-strings` before each '---' line works and doesn't break ytt, I don't quite understand "because (@ was erroneously interpreted as ytt syntax in some cases even though it wasnt (it was actually json path syntax within k8s crd definitions)".  Is it for performance consideration or any known bugs related ?

In Go Template, Ruby ERB Templating, Python Templating,  the inline text templating (i.e. `(@ ... @) and `(@= @)`) is always turned on (no need to turn it on explicitly).
