### ISSUE TITLE
remove item from array, but get append

### ISSUE THREAD

**Issue by Lwxiang** [k14s/ytt#592]
overlay
```yaml
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.all,expects="0+"
---
containers:
  #@overlay/match by=overlay.all,expects="0+"
  #@overlay/match-child-defaults expects="0+"
  - env:
      #@overlay/match by="name",expects="0+"
      #@overlay/remove
      - name: "hello"
```

plain
```
containers:
  - name: nginx
    env:
      - name: hello
        value: fff
  - name: foo
  - name: bar
 ```

What I expect is remove the name=hello item from all containers' env, but I get the following result:
```
containers:
- name: nginx
  env: []
- name: foo
  env:
  - name: hello
- name: bar
  env:
  - name: hello
```

In container "nginx" the result is expected, but in other 2 containers, the env has been appended.

**Comment by gcheadle-vmware** [comment]
Hi @Lwxiang 

Using [`@overlay/match by=overlay.subset`](https://carvel.dev/ytt/docs/latest/lang-ref-ytt-overlay/#overlaysubset) will allow you to match a node based on its value. What you have, 
```
#@overlay/match by=overlay.all,expects="0+"
- env:
``` 
will match all array items under `containers`, and if the item doesn't have an `env` key then it will add it. Using `overlay.subset` will only match on array items with the `env` key.

Secondly, the `@overlay/remove` action you have is removing the array item rather than the map item contained within, and then when the `#@overlay/match by="name",expects="0+"` matcher fails to find a `name` key, `ytt` will by default append array items. As a reminder, an overlay has two parts, a matcher and an action. The action occurs only when the matcher successfully matches. 
For an array item, if the matcher does not match, then the fallback action is to append.

I have rewritten your overlay to perform the removal that you desire:
```
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.all,expects="0+"
---
containers:
  #@overlay/match by=overlay.subset({"env": []}), expects="0+"
  - env:
      #@overlay/match by="name", when="1+"
      - 
        #@overlay/remove
        name: hello
```
To me, this overlay reads:
- for all documents
- that must have a `containers` map key
  - for array items that have a value of `{"env": []}`, a map with an item that has key `env` and an array value (there may be zero to many of these)
    - within `env`'s array  match items where has a map item `name:  hello` (continue if there is at least one match)
      - remove map item with key `name`

There are some difficult concepts embedded in this overlay (such as the lonely array item `-` on the third to last line), to learn more about how annotations find their node, see [ytt annotation guide.](https://carvel.dev/ytt/docs/latest/yaml-primer/#example-annotating-an-array)

Please let me know if you have additional questions, thank you for reaching out!

**Comment by gcheadle-vmware** [comment]
Also, check us out at on the kubernetes slack if you wanted an alternative way to ask questions.
https://kubernetes.slack.com/messages/carvel/

**Comment by Lwxiang** [comment]
Great! Thank you so much for your reply. Very detailed, that is indeed solved my problem.

I have some further considers,
our server provides some addition environment variables for k8s manifest, some env are added by default, while some env will not if it already set by user.

for example, I have 2 env
* always_append, it should be append to the every containers' env in Deployment.
* append_when_not_exist, it should be append to every containers' env in Deployment **if not exist**. If user already set it in their manifest, then we do nothing.

user's manifest
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
spec:
  template:
    spec:
      containers:
        - name: nginx
          env:
            - name: append_when_not_exist
              value: old
        - name: foo
```
after rendering, it should be
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
spec:
  template:
    spec:
      containers:
        - name: nginx
          env:
            - name: append_when_not_exist
              value: old
            - name: always_append
              value: new
        - name: foo
          env:
            - name: append_when_not_exist
              value: new
            - name: always_append
              value: new
```

according your comments, I think the overlay should be:
```
#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.all

#@overlay/match by=overlay.all,expects="0+"
---
spec:
  #@overlay/match missing_ok=True
  template:
    #@overlay/match missing_ok=True
    spec:
      #@overlay/match missing_ok=True
      containers:
        #@overlay/match by=overlay.all,expects="0+"
        #@overlay/match-child-defaults expects="0+"
        - env:
            #@overlay/append
            - name: "always_append"
              value: new
            #@overlay/match by="name",expects="0+"
            #@overlay/replace via=lambda left, right: left
            - name: "append_when_not_exist"
              value: new
```

the key point is, in array the action will be append if matcher failed, so
* for env name not exist, it append by default
* for env name exist, we let the matched array item be itself.

it works as expected.

**Comment by gcheadle-vmware** [comment]
Awesome! The overlay you wrote works as expected. One note is that by using this set of matchers:
```
#@overlay/match by=overlay.all, expects="0+"
---
spec:
  #@overlay/match missing_ok=True
  template:
    #@overlay/match missing_ok=True
    spec:
      #@overlay/match missing_ok=True
      containers:
```
any templates that do not have a top level `spec` key will error. Also any template that has a top level `spec`, but no `template` child key, will be merged with the overlay; for example:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
spec: 
  file: path/to/file.yml
```
with your overlay, renders as: 
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
spec:
  file: path/to/file.yml
  template:
    spec:
      containers:
      - env:
        - name: always_append
          value: new
        - name: append_when_not_exist
          value: new
```

This may not be a concern for you. However, if you *only* wanted to append your items to templates that contain the `spec`, `template`, `spec`, `containers` pattern, you can replace the beginning of your overlay with the following: 
```
#@overlay/match by=overlay.subset({"spec": {"template": {"spec": {"containers": []}}}})
---
spec:
  template:
    spec:
      containers:
```
This subset matcher will only match on documents with a top level `spec` key, whose value is contains a map with a `template` key, whose value is contains a map with a `spec` key, whose value is contains a map with a `containers` key, whose value is contains an array.

There can be a lot of information packed into a single overlay annotation, so there can be unintended consequences when sprinkling annotations throughout an overlay. I hope this helps and it feels like you have a good grasp on how to achieve the behavior you want. Closing this issue.
