### ISSUE TITLE
Inline Map Merge

### ISSUE THREAD

**Issue by damienleger** [k14s/ytt#602]
Hello, is there a way to do something like this

```
#@ def additional_items():
- item2
- item3
#@ end
---

#@ load("@ytt:template", "template")
foo:
  bar:
    - item1
    - #@ template.replace(additional_items())
```
(source: https://github.com/vmware-tanzu/carvel-ytt/issues/574#issuecomment-1007719765)

but with maps?

This doesn't work:

```
#@ def additional_items():
item2
item3
#@ end
---

#@ load("@ytt:template", "template")
foo:
  bar:
    item1
    #@ template.replace(additional_items())
```

**Comment by pivotaljohn** [comment]
Check out this example: https://carvel.dev/ytt/docs/v0.39.0/lang-ref-ytt-template/#add-a-new-item-to-the-labels-mapping

In this case, it could look like...
```
#@ def additional_items():
item2:
item3:
#@ end
---

#@ load("@ytt:template", "template")
foo:
  bar:
    item1:
    _: #@ template.replace(additional_items())
```
- note map items require (at a minimum) the `:` token
- we're using `_` as a map item key, but any legal key will work... it'll just get replaced.
