### ISSUE TITLE
- struct has no .scrapeTimeout field or method

### ISSUE THREAD

**Issue by ramkrishna2k3** [k14s/ytt#635]
I have a weird issue. Unable to resolve, Kindly help

error : 
```
**ytt: Error:
- struct has no .scrapeTimeout field or method
    in <toplevel>
      config.yml:257 |       scrapeTimeout: #@ data.values.podMonitor.scrapeTimeout**
```

I pass the value in config.yml from values.yml

**config.yml**
```
---
#! Source: tomcat/templates/podmonitor.yaml
#@ if data.values.podMonitor.enabled:
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: tomcat
  namespace: #@ data.values.podMonitor.namespace
  labels:
    app.kubernetes.io/name: tomcat
    helm.sh/chart: tomcat-10.1.12
    app.kubernetes.io/instance: release-name
spec:
  podMetricsEndpoints:
    - port: "metrics"
      path: /metrics
      interval: #@ data.values.podMonitor.interval
      _scrapeTimeout: #@ data.values.podMonitor.scrapeTimeout_
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/name: tomcat
      helm.sh/chart: tomcat-10.1.12
      app.kubernetes.io/instance: release-name
#@ end
```

**values.yml**
```
podMonitor:
  enabled: false
  #@schema/desc "Namespace in which Prometheus is running"
  namespace: monitoring
  #@schema/desc "Interval at which metrics should be scraped."
  interval: 30s
  #@schema/desc "Specify the timeout after which the scrape is ended"
  scrapeTimeout: 30s
```
**But when I give podMonitor, enabled false then reconcile is succeed, but when i give false reconcile get failed.** 

**pkginstall.yml**
```
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tomcatapp-demo
spec:
  serviceAccountName: default-ns-sa
  packageRef:
    refName: tomcatapp.bitnami.vmware.com
    versionSelection:
      constraints: 10.1.12
  values:
  - secretRef:
      name: tomcatapp-demo-values
---
apiVersion: v1
kind: Secret
metadata:
  name: tomcatapp-demo-values
stringData:
  values.yml: |
    ---
    podMonitor:
      enabled: true       (note: false works fine)
    prometheusRule:
      enabled: true
    ingress:
      enabled: true
```

---
2022-03-21 (@pivotaljohn) — added code fences to make clearer the indentation of the provided YAML files (indentation doesn't show up in plain markdown).
