### ISSUE TITLE
How to apply overlay/match-child-defaults to data values document?

### ISSUE THREAD

**Issue by guludo** [k14s/ytt#65]
I'm having a hard time use `#@overlay/match-child-defaults` with the "values" document. For example, consider the following layout:

```
default.yml
values1.yml
values2.yml
config.yml
```

With the following content:

**default.yml**:
```yaml
#@data/values
---
a: 1
b: 2
foo:
    bar: 1
```

**values1.yml**
```yaml
#@data/values
---
#@overlay/match-child-defaults missing_ok=True
foo:
    baz: 1
```

**values2.yml**
```yaml
#@data/values
--- #@overlay/match-child-defaults missing_ok=True
c: 2
```

**config.yml**
```yaml
#@ load("@ytt:data", "data")
#@ load("@ytt:template", "template")

--- #@ template.replace([data.values])
```

When applied to a map, it works fine:
```bash
$ ytt -f default.yml -f values1.yml -f config.yml 
a: 1
b: 2
foo:
  bar: 1
  baz: 1
```

But, I get an error when applied to the document: 
```bash
$ ytt -f default.yml -f values2.yml -f config.yml 
Error: Map item (key 'c') on line values2.yml:3: Expected number of matched nodes to be 1, but was 0
```

Am I misplacing the annotation?
