### ISSUE TITLE
For loop inside yaml templating

### ISSUE THREAD

**Issue by malcolm061990** [k14s/ytt#734]
Hi.
I need to use "for" loop inside yaml templating.
I have config.yaml:
```yaml
#@data/values
---
logging:
  apps: [[app1, ns1], [app2, ns2]]
```

template.yaml:
```yaml
#@ load("@ytt:data", "data")
#@yaml/text-templated-strings
---
spec:
  source:
    #@ for app,ns in data.values.logging.apps: #! it works
    app: #@ app
    ns: #@ ns
    #@ end
    helm:      
      values: |
        config:
          inputs: |
            #! here I need "for" loop. Something like:
            #@ for app,ns in data.values.logging.apps:
            [INPUT]
              app: #@ app
              ns: #@ ns
            #@ end

            #! How can I use "for" loop inside yaml templating?
```

I want to get:
```yaml
spec:
  source:
    helm:      
      values: |
        config:
          inputs: |
            [INPUT]
              app: app1
              ns: ns1
            [INPUT]
              app: app2
              ns: ns2
```
