### ISSUE TITLE
Is there a way to iterate a template over multiple data files with matching schema?

### ISSUE THREAD

**Issue by ryankilroy** [k14s/ytt#746]
Hi there! I have multiple `@data/values` files that are used for different branches. e.g.

``` 
# main.yml
#@data/values
---
main:
  dependency_a_version: 1.0.0
  dependency_b_version: 1.0.1
```

```
# develop.yml
#@data/values
---
develop:
  dependency_a_version: 2.0.0
  dependency_b_version: 2.0.2
```

And those files feed into something where I'd like to do:

```
# ci.yml
#@ load("@ytt:data", "data")

branch_dependencies:
  # for/end branch in ["main", "develop"]:
  branch_(@= branch @):
  - #@ data.values.(@= branch @)
```
Where I'd like the resulting yml to be:

```
branch_dependencies:
  branch_main:
  - dependency_a_version: 1.0.0
  - dependency_b_version: 1.0.1
  branch_develop:
  - dependency_a_version: 2.0.0
  - dependency_b_version: 2.0.2
```

This is obviously a much simpler example than what I am actually trying to do, but hopefully the general idea comes across. I have multiple `values.yml` files that obey the same schema and would like a way to merge them all into one main `yml` file with a pre-existing template.

The structure of the actual values files can also change, I feel like having a unique top-level key could cause schema issues, but I'm just not sure how else to iterate over the files without a unique identifier of some kind. Can you somehow specify the source file for a specific `data.values` read?

Apologies in advance if I missed something in my exploration of the docs, I couldn't quite figure out the combination of for loops, overlays, and templates to get this to do what I wanted.

**Comment by mamachanko** [comment]
@ryankilroy As far as I know you can only have one `#@data/values`-annotated document. Another way is to specifically provide data value files. 

```yaml
#! develop.yml
---
develop:
  dependency_a_version: 2.0.0
  dependency_b_version: 2.0.2
```
```yaml
#! main.yml
---
main:
  dependency_a_version: 1.0.0
  dependency_b_version: 1.0.1
```
```yaml
#! ci.yml
#@ load("@ytt:data", "data")
#@ load("@ytt:template", "template")

#@ def branch_deps():
#@   bds = {}
#@   for branch in ["main", "develop"]:
#@     bds.update({"branch_{}".format(branch): getattr(data.values, branch)})
#@   end
#@   return bds
#@ end

branch_dependencies: #@ branch_deps()
```
```shell
ytt --file ci.yml --data-values-file main.yml --data-values-file develop.yml
```
Yields:
```yaml
branch_dependencies:
  branch_main:
    dependency_a_version: 1.0.0
    dependency_b_version: 1.0.1
  branch_develop:
    dependency_a_version: 2.0.0
    dependency_b_version: 2.0.2
```

I am sure @jtigger has much slicker approaches at hand.
