### ISSUE TITLE
[Question] Is there a way to force the type of a value using ytt:data?

### ISSUE THREAD

**Issue by arielly-parussulo** [k14s/ytt#756]
## Context
We use ytt data to handle template to use in our deployment. One of the values that we use in our deployment is the git commit as a tag for our Docker Images. 
Normally it works fine as YTT identify the git commit as a string and generates the final YAML file like:

```yaml
parameters:
  app:
    tag: 427d910 # my git commit id
``` 

## Problem
We are facing an issue with some of our git commits (e.g. `357e009`) where YTT identify the value as a the number `3.57e+11` the final YAML becomes something like:

```yaml
parameters:
  app:
    tag: 3.57e+11
```

My question is if there is a way to force YTT to understand values like 357e009 as a string.
