### ISSUE TITLE
Edit a rule in a Kubernetes ClusterRole object

### ISSUE THREAD

**Issue by damienleger** [k14s/ytt#762]
Hello,

I have this Kubernetes ClusterRole object, I try to edit one rule and add the "list" verb. I don't succeed in having a good `#@overlay/match` line. I just give up, please help me 🙏 

```
#@ load("@ytt:overlay", "overlay")
---
kind: ClusterRole
metadata:
  name: test
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  - nodes/spec
  - nodes/proxy
  - nodes/stats
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get

#@overlay/match by=overlay.all, expects=1
---
rules:
#!overlay/match by=(lambda x,l,r: "endpoints" in l["resources"])
#@overlay/match by=(lambda x,l,r: yaml.encode([{"resources":["endpoints"]}]) in l, expects=1
- resources:
  - endpoints
  verbs:
  - get
  - list
```

P.S.: On a side node, I love YTT and array but EVERYTIME I need to work with arrays like this there is zero useful doc it's just a nightmare. This is all about lambda, left, right, index, yamlfragment and stuff. All of this is gibberish to me. I have a really poor understanding of what in "left", and "right" (also this one seems never been used?!) without example. And it's really frustrating to being "obliged" to ask for help for something that seems so basic. I have found something that could help on github issue if only the answer wasn't that enigmatic https://github.com/vmware-tanzu/carvel-ytt/issues/317

**Comment by mamachanko** [comment]
@damienleger thank you for your feedback! We have empathy for your sentiment 💯.

This should provide you with the desired outcome:

```yaml
#@ load("@ytt:overlay", "overlay")

---
kind: ClusterRole
rules:
  - apiGroups:
    - ""
    resources:
    - endpoints
    verbs:
    - get
  - apiGroups:
    - other
    resources:
    - other
    verbs:
    - other

#@overlay/match by=overlay.subset({"kind": "ClusterRole"})
---
rules:
  #@overlay/match by=lambda i,l,r: "endpoints" in list(l["resources"]), expects="0+"
  - verbs:
    - list
```

Yields:
```yaml
kind: ClusterRole
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
- apiGroups:
  - other
  resources:
  - other
  verbs:
  - other
```

In the larger picture, where or how would you have expected docs on https://carvel.dev/ytt/docs/latest/ ? I am handing you a magic wand 🪄.

**Comment by damienleger** [comment]
Thanks @mamachanko, I've tweaked a bit for my case and it's working

```
#@ load("@ytt:overlay", "overlay")
---
kind: ClusterRole
metadata:
  name: test
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  - nodes/spec
  - nodes/proxy
  - nodes/stats
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get

#@overlay/match by=overlay.subset({"kind": "ClusterRole"})
---
rules:
  #@overlay/match by=lambda i,l,r: "resources" in l and "endpoints" in list(l["resources"]), expects="0+"
  - verbs:
    - list
```

> In the larger picture, where or how would you have expected docs on https://carvel.dev/ytt/docs/latest/ ? I am handing you a magic wand 🪄.

First of all I'd like to apologize for my not so kind P.S. phrasing. I wrote this issue after 2h+ of battle with the overlay.match and was upset.

About doc, imho
- there should be example of overlay on Deployment pod container, for instance to add securityContext or edit resources for instance for one or all containers in a pod (simple list to match by index or container name)
- there should be more complex example like this ClusterRole modification because of the nested list situation

I'd say more explanation of the lambda would be great also, or some specific section for troubleshooting: how to display what's in index/left/right if it's possible. I had zero ideas I needed to use list() function for my case and still not sure actually. I suppose it's because left is yamlfragment https://carvel.dev/ytt/docs/v0.43.0/lang-ref-ytt-overlay/#custom-overlay-matcher-functions . Lambda development looks too much trial-and-error imho.
