### ISSUE TITLE
Is there a way to iterate a struct?

### ISSUE THREAD

**Issue by JohnHillegass** [k14s/ytt#79]
For example if I have:
```
#@data/values
---
steps:    
    mark:
      filters: '< 3'
      actions: 'add tag less than 3'
    unmark:
      filters: '> 3 && < 5'
      actions: 'add tag greater than 5'
    delete:
      filters: '> 5'
      actions: 'delete thing'
```
and want to display it like this:
```
#@ load("@ytt:data", "data")
#@ for step in listdata.values.steps:
    - name: #@ step
#@ end
```
I am getting this error and am currently unable to find a work around

Error: 
- list: for parameter 1: got struct, want iterable
