### ISSUE TITLE
Can you conditionally render a YAML based on flag in schema?

### ISSUE THREAD

**Issue by Mercanuis** [k14s/ytt#807]
Hello! First time YTT-er here.

I was trying to work with a situation where I would like to try the following

"If a flag is set to false, then ignore the YAML file tied to it via a conditional"

## Context
I'm writing several files to template out Backstage/Techdocs files that scaffold a Developer Portal. These files are a bit unwieldy and by templating them the idea is to abstract that logic from our end-users

This is the Schema
```
#! value-schema.yaml
#! Used by YTT to set values to use for the scaffold
#@data/values-schema
---

owner:
  name: MY-NAME
  namespace: MY-NAMESPACE

techdocs:
  #! The default directory root for your documents
  #! If you change it from ".", the name MUST match
  #! what you set for catalog.mkdocs.docdir
  docdir: "."

domain:
  name: MY-DOMAIN
  title: MY-DOMAIN-TITLE

system:
  name: MY-SYSTEM
  title: MY-SYSTEM-TITLE

component:
  name: MY-COMPONENT
  title: MY-COMPONENT-TITLE

  #@schema/validation one_of=["documentation", "library", "service", "website"]
  type: documentation

  #@schema/validation one_of=["deprecated", "experimental", "production"]
  lifecycle: experimental

  hasApis: false <===== HERE
  providesApis:
    - MY-API

api:
  name: MY-API
  title: MY-API-TITLE

  #@schema/validation one_of=["openapi"]
  type: openapi

  #@schema/validation one_of=["deprecated", "experimental", "production"]
  lifecycle: experimental

  filePath: /api/my-api.yaml
```

`hasApis` is the flag I would like to use to say that if its set to `false`, we want to not template out a specific skeleton, shown here:

```
#@ load("@ytt:data", "data")
#@ load("/lib/format.star", "fmtName", "fmtOwner")
#@ load("/lib/labels.lib.yaml", "apiref", "docref")

#! #nonk8s
#@ if/end data.values.component.hasApis:   <===== HERE
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: #@ fmtName(data.values.api.name, "api")
  #@ if/end hasattr(data.values.owner, "namespace"):
  namespace: #@ data.values.owner.namespace
  title: #@ data.values.api.title
  description: This document is auto-scaffolded, feel free to change this description
  annotations: #@ docref(data.values.techdocs.docdir)
spec:
  type: #@ data.values.api.type
  owner: #@ fmtOwner(data.values.owner.name)
  system: #@ data.values.system.name
  lifecycle: #@ data.values.api.lifecycle
  definition: #@ apiref(data.values.api.filePath)
```

## Questions
* Is this even feasible? And if so...
* Is schema or overlays the recommended way to do this? I am (still) reading the documents but its not very clear so far what is the course of action recommended by YTT (if there is one)

Thanks!

**Comment by Mercanuis** [comment]
Update: so I figured out a workaround, but not sure if this is the intended way to handle this use-case
```
#@ load("@ytt:data", "data")
#@ load("/lib/format.star", "fmtName", "fmtOwner")
#@ load("/lib/labels.lib.yaml", "apiref", "docref")

#! #nonk8s
#@ if data.values.component.hasApis:
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: #@ fmtName(data.values.api.name, "api")
  #@ if/end hasattr(data.values.owner, "namespace"):
  namespace: #@ data.values.owner.namespace
  title: #@ data.values.api.title
  description: This document is auto-scaffolded, feel free to change this description
  annotations: #@ docref(data.values.techdocs.docdir)
spec:
  type: #@ data.values.api.type
  owner: #@ fmtOwner(data.values.owner.name)
  system: #@ data.values.system.name
  lifecycle: #@ data.values.api.lifecycle
  definition: #@ apiref(data.values.api.filePath)
#@ else:
#@ end
```

Where if the flag is `false` the resulting YAML is empty and thus, no file is produced
