### ISSUE TITLE
Empty Array when trying to Render

### ISSUE THREAD

**Issue by Mercanuis** [k14s/ytt#811]
HI there 👋  sorry for the probably very newbie question as I'm still learning to use YTT but I am trying to understand the following

Reading the documentation on [Defaults for Arrays](https://carvel.dev/ytt/docs/v0.44.0/lang-ref-ytt-schema/#defaults-for-arrays), the following example is given:

```
#@data/values-schema
---
app_domains:
- ""

databases:
- name: ""
  adapter: postgresql
  host: ""
  port: 5432
  user: admin
  secretRef:
    name: ""
```

> app_domains is [] by default. Each item in the array must be a string.

Using this as the template, my team is building scaffolding out for building YAML for a Developer Portal. The data schema is like this

```
#! value-schema.yaml
#! Used by YTT to set values to use for the scaffold
#@data/values-schema
---

owner:
  name: MY-NAME
  namespace: MY-NAMESPACE

techdocs:
  #! The default directory root for your documents
  #! If you change it from ".", the name MUST match
  #! what you set for catalog.mkdocs.docdir
  docdir: "."

domain:
  name: MY-DOMAIN
  title: MY-DOMAIN-TITLE
  description: MY-DOMAIN-DESCRIPTION

system:
  name: MY-SYSTEM
  title: MY-SYSTEM-TITLE
  description: MY-SYSTEM-DESCRIPTION

component:
  name: MY-COMPONENT
  title: MY-COMPONENT-TITLE
  description: MY-COMPONENT-DESCRIPTION

  #@schema/validation one_of=["documentation", "library", "service", "website"]
  type: documentation

  #@schema/validation one_of=["deprecated", "experimental", "production"]
  lifecycle: experimental

  hasApis: true
  apis:
    - MY-API
```

`apis` is an array of strings, however, when referenced in the template

```
#@ load("@ytt:data", "data")
#@ load("/lib/format.star", "fmtName", "fmtOwner")
#@ load("/lib/labels.lib.yaml", "docref")

#! #nonk8s
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: #@ fmtName(data.values.component.name, "component")
  #@ if/end hasattr(data.values.owner, "namespace"):
  namespace: #@ data.values.owner.namespace
  title: #@ data.values.component.title
  description: #@ data.values.component.description
  annotations: #@ docref(data.values.techdocs.docdir)
spec:
  type: #@ data.values.component.type
  owner: #@ fmtOwner(data.values.owner.name)
  system: #@ data.values.system.name
  lifecycle: #@ data.values.component.lifecycle
  providesApis: #@ data.values.component.apis <--- Array is here
```

`providesApis` always returns an empty array. I am not sure why given that there is a value in the schema. I feel I'm missing something quite straight forward, any advice? I was unable to find any examples on point, and every one is a use of an overlay: is an overlay the only way to populate an array in a template? 

Thanks!
