### ISSUE TITLE
Split data into more than one file

### ISSUE THREAD

**Issue by maudrid** [k14s/ytt#820]
Hi. I'm very new to ytt and I hope someone can point me in the right direction.
I'm trying to do something seemingly simple, but I'm not able to get it to work.
I have created a config.yml and I have a data1.yml.
I can then use `#@ load("@ytt:data", "data")` and reference the values ex: `attribute1: #@ data.values.att1` and this works.
Some of the values that I have this the data1.yml, I want to place in a different file for maintenance purposes, now I have 3 files:
config.yml
```
#@ load("@ytt:data", "data")

attribute1: #@ data.values.att1
attribute2: #@ data.values.att2
```
data1.yml
```
#@data/values
---
att1: "value1"
```
data2.yml
```
#@data/values
---
att2: "value2"
```

This produces the following error:
```
Overlaying data values (in following order: data1.yml, data2.yml): Document on line data2.yml:2: Map item (key 'att2') on line data2.yml:3: Expected number of matched nodes to be 1, but was 0
```
I understand that it is trying to overlay the 2 data files, but that is not what I want.
I can add `att2` to the data1.yml file to remove this error, but that defeats what I set out to do.

That being said, maybe I'm using this all wrong in the firs place.
Here is a real example of why I'm trying to do this:
config.yml
```
 grafana:
    image: gitlab.company.com:4567/myProject/grafana:#@ data.values.branch or "1.9"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 400m
    #@ if data.values.swarm:
      placement:
        constraints:
          - "node.labels.appserver==true"
      labels: #@ data.values.grafana_labels
    #@ else:
    labels: #@ data.values.grafana_labels
    #@ end
```
labels.yml
```
#@data/values
---
grafana_labels:
  - traefik.enable=true
  - traefik.http.routers.grafana.entrypoints=web
```
settings.yml
```
#@data/values
---
swarm: true
branch: "master"
```
So I would not want to mix the values from the labels and the settings files. Since the settings will change all the time and the labels are static. But by using labels as data, I can maintain one copy of labels.
