### ISSUE TITLE
[Question]::Can we replace and Remove yaml keys with single configuration ?

### ISSUE THREAD

**Issue by UPADHYA28** [k14s/ytt#827]
Hi Team,

This question might seem very basic, but i am a new user of `ytt` and still in exploration mode. 

I have following templates. 
**Base Template:**
```
`---
apiVersion: 1
specification: 
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              myConfiguration:
                description: Customized Configuration
`
```

**Key Replace Template:**

```
`
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@overlay/match by=overlay.all
---
apiVersion: 1
specification: 
  versions:
  #@overlay/match by=overlay.all, expects="1+"
    - schema:
        #@overlay/replace via=lambda left, right: {"properties": right}
        openAPIV3Schema:
            spec:
              new_myConfiguration:
              #@overlay/replace via=lambda left, right: {"properties": right}
                new_description: Modified Configuration
              new_key: avinash
`
```

**Key_Remove_Template:**

```
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@overlay/match by=overlay.all
---
apiVersion: 1
specification: 
  versions:
  #@overlay/match by=overlay.all, missing_ok=True
    - schema:
        openAPIV3Schema:
          properties:
            spec:
              #@overlay/match when=lambda right: data.values.client == "local_client"
              #@overlay/remove
              new_myConfiguration:
```

So basically i am trying to rename `myConfiguration` provided `client !="local_client"`, and if then remove `myConfiguration` altogether.
