### ISSUE TITLE
How to use overlay annotation with plain yaml objects

### ISSUE THREAD

**Issue by Hugal31** [k14s/ytt#839]
My goal is to have overlayed data/values that result in a dictionary of objects. Then, I apply an operation to replace missing fields in each of those sub-objects by a default object, also defined in the overlayed data/values. It works well, however I can't specify the usual overlay annotations, as `#@overlay/replace` for the arrays.

I have those two files:

test.values.yaml
```yaml
#@ load("@ytt:overlay", "overlay")
#@data/values
#@overlay/match-child-defaults missing_ok=True
---
root:
  default:
    x: 1
    'y': 2
    array: [300, 400]

  high:
    x: 5
    array: [600]

  low:
    'y': -1
```

and test.yaml:

```yaml
#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ default = data.values.root.default
root: #@ {k: overlay.apply(default, v) for k, v in dict(data.values.root).items() if k != "default"}
```

The result :
```yaml
root:
  high:
    x: 5
    "y": 2
    array:
    # Here the items are appended
    - 300
    - 400
    - 600
  low:
    x: 1
    "y": -1
    array:
    - 300
    - 400
```

Expected result:
```yaml
root:
  high:
    x: 5
    "y": 2
    array:
    - 600
  low:
    x: 1
    "y": -1
    array:
    - 300
    - 400
```

How can I achieve this?
