### ISSUE TITLE
Support default value for `any` type

### ISSUE THREAD

**Issue by LittleWat** [k14s/ytt#883]
**Describe the problem/challenge you have**

I want set the default value for `any` type but I can't.

Here is the example.

- schema.yaml

```yaml
#@data/values-schema
---
test:
  #@schema/type any=True
  optional_config:
    param1: "a"
    param2: "b"
```

- template.yaml

```yaml
#@ load("@ytt:data", "data")

conf: #@ data.values.test.optional_config
```

- value.yaml

```yaml
#@data/values
---
test:
  optional_config:
    param3: "c"

```

```shell
$  ytt -f value.yaml -f schema.yaml -f template.yaml
ytt: Error: Overlaying data values (in following order: value.yaml):
  Document on line value.yaml:2:
    Map item (key 'test') on line value.yaml:3:
      Map item (key 'optional_config') on line value.yaml:4:
        Map item (key 'param3') on line value.yaml:5:
          Expected number of matched nodes to be 1, but was 0
```

**Describe the solution you'd like**

In the example, the expected output is:

```yaml
conf:
    param1: a
    param2: b
    param3: c
```

I hope this is supported 🙏 

Or I would be glad if you could share the workarounds for this 🙇‍♂️ 

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by LittleWat** [comment]
I found the workaround for this. It was necessary to write the Starlark code, though.

- schema.yaml

```yaml
#@data/values-schema
---
test:
  #@schema/type any=True
  optional_config: null

_default_optional_config:
  param1: a
  param2: b
```

- template.yaml

```yaml
#@ load("@ytt:data", "data")
#@ load("@ytt:struct", "struct")

#@ def combine_with_default(user_config, default_config):
#@  result = struct.decode(default_config)
#@  if user_config:
#@      result.update(struct.decode(user_config))
#@  end
#@  return result
#@ end

conf: #@ combine_with_default(data.values.test.optional_config, data.values._default_optional_config)
```

- value.yaml

```yaml
#@data/values
---
test:
  optional_config:
    param1: "aaa"
    param3: "c"
    parma4:
      param4_4: "ddd"
```

and here is the execution result:

```shell
$  ytt -f schema.yaml -f template.yaml -f value.yaml
conf:
  param1: aaa
  param2: b
  param3: c
  parma4:
    param4_4: ddd
```

**Comment by prembhaskal** [comment]
@LittleWat What you are trying to achieve can be easily done using an overlay

- template.yml
```yaml
#@ load("@ytt:data", "data")

conf: #@ data.values.test.optional_config
```
- default-schema.yml
```yaml
#@data/values-schema
---
test:
  #@schema/type any=True
  optional_config:
    param1: a
    param2: b
```

- val.yml
```yaml
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.all
---
conf:
  #@overlay/match missing_ok=True
    param3: c
```

**Comment by prembhaskal** [comment]
you can even overlay data values instead of overlaying final results using below variant of val.yml

- val.yml (overlay data-values)
```yaml
#@ load("@ytt:overlay", "overlay")
#@data/values

#@overlay/match by=overlay.all
---
test:
  optional_config:
  #@overlay/match missing_ok=True
    param3: c
    

```
