### ISSUE TITLE
Add an optional boolean to not escape html during json encoding

### ISSUE THREAD

**Issue by WnP** [k14s/ytt#890]
By default the golang encode does escape problematic HTML characters inside JSON quoted strings. Which may leads to undesired behavior.

A typical example is when you are using the [argocd-vault-plugin](https://github.com/argoproj-labs/argocd-vault-plugin) syntax inside a json string, which looks like this:

```yaml
#@data/values
---
credentials:
  username: bob
  password: <path:/to/bob/password>
```
Then if I want to create a secret with

```yaml
#@ load("@ytt:data", "data")
#@ load("@ytt:json", "json")
stringData: #@ json.encode(data.values.credentials, indent=2)
```

Then it compiles to:
```yaml
stringData: |-
  {
    "username": "bob",
    "password": "\u003cpath:/to/bob/password\u003e"
  }
```
Which obviously isn't what we want.

It would be nice if we can call [Encode.SetEscapeHTML](https://pkg.go.dev/encoding/json#Encoder.SetEscapeHTML) somehow to prevent that.
