### ISSUE TITLE
[overlay] support matching multiple map items via overlay.all

### ISSUE THREAD

**Issue by cppforlife** [k14s/ytt#90]
would like for following to support

```yaml
#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({"uaa": true})
---
clients:
  #@overlay/match by=overlay.all,expects="1+"
  _:
    secret: foo
```

to support updating following:

```yaml
---
uaa: true
clients:
  client1:
    secret: blah1
  client2:
    secret: blah2
```

to result in

```yaml
---
uaa: true
clients:
  client1:
    secret: foo
  client2:
    secret: foo
```

**Comment by jtigger** [comment]
I assume that we'd technically want an `#@overlay/match` on the parent (i.e. `clients`) to indicate that map is an overlay... yeah?  Or is it in scope for this work to infer that if any child node is annotated with `#@overlay...` that the whole graph is an overlay?

**Comment by cppforlife** [comment]
@jtigger snippets were implying that they were inside a regular overlay yaml doc. updated that to make that more clear.

**Comment by cppforlife** [comment]
to be clear this should be generic behaviour so something like this should also work:

```yaml
#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({"uaa": true})
---
clients:
  #@overlay/match by=overlay.subset({}),expects="1+"
  _:
    secret: foo
```
