### ISSUE TITLE
Overlaying list on schema renders incorrectly

### ISSUE THREAD

**Issue by henry-spanka** [k14s/ytt#912]
**What steps did you take:**

I expect b.yaml to append item "var1" to *vars* list in each app. However the item is appended twice (or more depending on how many items are in apps).

schema.yaml
```yaml
#@data/values-schema
---
apps:
  - name: ""
    vars:
      - ""
```

a.yaml
```yaml
#@data/values
---
apps:
  - name: app1
  - name: app2
```

b.yaml
```yaml
#@data/values
#@ load("@ytt:overlay", "overlay")
---
apps:
  #@overlay/match by=overlay.all, expects="1+"
  - vars:
    - var1
```

```shell
ytt -f schema.yaml -f a.yaml -f b.yaml --data-values-inspect
```

**What happened:**

"var1" is appended to each *vars* list twice.

```yaml
apps:
- name: app1
  vars:
  - var1
  - var1
- name: app2
  vars:
  - var1
  - var1
```

**What did you expect:**

"var1" appended once to *vars* list.

```yaml
apps:
- name: app1
  vars:
  - var1
- name: app2
  vars:
  - var1
```

**Anything else you would like to add:**

Setting *vars* to an empty list in a.yaml explicitly resolves this issue, however it's not the same semantically (default value from schema file gets lost).

```yaml
#@data/values
---
apps:
  - name: app1
    vars: []
  - name: app2
```

Additionally, defining b.yaml as following to only match on name=app1, appends item to every list item (behaving like overlay.all).

```yaml
#@data/values
#@ load("@ytt:overlay", "overlay")
---
apps:
  #@overlay/match by=overlay.map_key("name"), expects="1+"
  - name: app1
    vars:
    - var1
```

**Environment:**

- ytt version (use `ytt --version`):
ytt version 0.49.0
- OS (e.g. from `/etc/os-release`):
macOS 14.4.1 M1

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by prembhaskal** [comment]
https://carvel.dev/ytt/#gist:https://gist.github.com/prembhaskal/626f1264d3ab6783d7c42ccf92eaeafd  added a gist for simpler reproducing of issue.

**Comment by prembhaskal** [comment]
few more illustrating similar issues
- https://carvel.dev/ytt/#gist:https://gist.github.com/prembhaskal/e9fc5954c90eecd980c99533e3770070
  - duplicated for all key not just matched
- https://carvel.dev/ytt/#gist:https://gist.github.com/prembhaskal/cffd92d9678d4109d13d9f27b15e4e2a
  - duplicated for only cases where array was already empty.

**Comment by praveenrewar** [comment]
@henry-spanka You can update your `b.yaml` to something like this
```yaml
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.all
---
apps:
  #@overlay/match by=overlay.all, expects="1+"
  - vars:
    - var1
```

- Remove `#@data/values` as this is an overlay
- Add an overlay match at `apps` level to match all apps

Now if you run `ytt -f config  --data-values-inspect | ytt -f ovr -f-`, you should get
```yaml
apps:
- name: app1
  vars:
  - var1
- name: app2
  vars:
  - var1
```
(The need to use ytt twice is because you don't have a config to load the data values and you are using data-values-inspect)
