### ISSUE TITLE
reference values from overlay subsets

### ISSUE THREAD

**Issue by ghost** [k14s/ytt#933]
**Describe the problem/challenge you have**
I'm trying to set a label on multiple resources but with a dynamic value that includes the resource name.  

```yaml
#@ load("@ytt:overlay", "overlay")

#@overlay/match expects="0+", by=overlay.subset({"kind": "Deployment"})
---
metadata:
 #@overlay/match missing_ok=True
 labels:
  #@overlay/match missing_ok=True
  foo: <deployment.metadata.name>-bar #! <---------- dynamically set metadata.name of the same matching resource
```

**Describe the solution you'd like**
I want to be able to reference a value from overlay subsets.

**Anything else you would like to add:**

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
