### ISSUE TITLE
[bug] `overlay/match` on array item incorrectly errors (and with wrong expectation)

### ISSUE THREAD

**Issue by jtigger** [k14s/ytt#94]
This input:

`test.yml`[1]
```
  1 ---
  2 clients:
  3 - client1:
  4     secret: blah1
  5 - client2:
  6     secret: blah2
  7
  8 #@ load("@ytt:overlay", "overlay")
  9 #@overlay/match by=overlay.all
 10 ---
 11 clients:
 12 #@overlay/match by=overlay.all,expects="1+"
 13 - client1:
 14     secret: foo
```

... yields this error message ...

```
ytt: Error: Overlaying (in following order: test.yml): Document on
line test.yml:10: Map item (key 'clients') on line test.yml:11: Array
item on line test.yml:13: Map item (key 'client1') on line
test.yml:13: Expected number of matched nodes to be 1, but was 0
```

Instead, I expect this output:

```yaml
---
clients:
- client1:
    secret: foo
- client1:
    secret: foo
```
---
[1] https://get-ytt.io/#gist:https://gist.github.com/jtigger/a3dbb1bb167452e288692e32127a4bf5

**Comment by cppforlife** [comment]
error message is correct. default behaviour is merge, hence it's telling you that second array item doesnt have client1 key already (ie it's not annotated with missing_ok=True if that's indeed what you wanted to do). alternatively to get your expected result you should add overlay/replace to array item:

```
---
clients:
- client1:
    secret: blah1
- client2:
    secret: blah2

#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.all
---
clients:
#@overlay/match by=overlay.all,expects="1+"
#@overlay/replace
- client1:
    secret: foo
```
