### ISSUE TITLE
`schema/type any=True` breaks schema composition

### ISSUE THREAD

**Issue by Zebradil** [k14s/ytt#945]
**What steps did you take:**

File: 1.schema.yaml

```
#@data/values-schema
---
#@schema/type any=True
something: {}
```

File: 2.schema.yaml

```
#@data/values-schema
---
something:
  #@overlay/match missing_ok=True
  list:
    - name: ""
```

File: values.yaml

```
#@data/values
---
something:
  list:
    - name: "one"
    - name: "two"
```

Command:

```
ytt -f . --data-values-inspect
```

**What happened:**

```
something:
  list:
  - name: ""
  - name: one
  - name: two
```

**What did you expect:**

```
something:
  list:
  - name: one
  - name: two
```

**Anything else you would like to add:**

For some reason, when using the `schema/type any=True` annotation, ytt adds an item from the additional schema to the resulting list.
Without this annotation, the result doesn't contain items from the schema, as expected.

File: 1.schema.yaml

```
#@data/values-schema
---
something: {}
```

**Environment:**

- ytt version (use `ytt --version`): ytt version 0.51.1
- OS (e.g. from `/etc/os-release`): MacOS 15.3.1

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by Zebradil** [comment]
activity

**Comment by Zebradil** [comment]
activity

**Comment by joaopapereira** [comment]
@100mik @devanshuVmware can one of you take a look at this issue?

**Comment by Zebradil** [comment]
Still valid

**Comment by Zebradil** [comment]
valid

**Comment by Zebradil** [comment]
Valid

**Comment by Zebradil** [comment]
Unstale

**Comment by Zebradil** [comment]
Unstale

**Comment by joaopapereira** [comment]
There is no way for me to apologize for this long list of Stale and Unstale :(
I am no expert in ytt but I am going to give this a shot.

---

After going through some debugging session and trying to understand the problem I feel like ytt is working as intended, but first let me try to get more information.
Why would you place a Overlay inside a Schema?
What are yll trying to archive with this Schema?

I might be on the wrong here but the Schemas are meant to be used to define the data structure that you expect the users to provide, while Overlay's are used to in some way manipulate the data.
This being said the way that ytt works is that it basically overlays everything on top of each other running the Overlay annotation as it does it.
Let me try to tell you what I see:
1. Process 1.schema.yaml
Output is
```yaml
---
#@schema/type any=True
something: {}
```
2. Process 2.schema.yaml
Output is:
```yaml
---
#@schema/type any=True
something: 
  list:
     - name: ""
```

And this is the final Schema, so basically what that Overlay checks if the list exists and it does not exist in the base schema so it appends to something the thing you told it to append even if there is no node `list`.

Given the above and my understanding on ytt it feels like this is not a bug but the way it is intended to work, because the the Schema itself serves as the base for the generation of your yaml.

But let me know what do you think.
