### ISSUE TITLE
overlay/replace on a map replaces keys, not only values

### ISSUE THREAD

**Issue by kralikba** [k14s/ytt#946]
**What steps did you take:**
I tried applying overlay/replace to all child elements' values.

```
a:
 a1:
   a: 1
   b: 2

#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.all
---
a:
#@overlay/match by=overlay.all, expects="1+"
#@overlay/replace
 _:
   a: 1
   b: 3
```

**What happened:**
Not only the values, but their key was replaced as well (to the dummy placeholder value).
```
a:
  _:
    a: 1
    b: 3
```
Because of this, matching `overlay.all` won't really work, as for multiple child items, this will cause a duplicate key error.

**What did you expect:**
That only the values are replaced
```
a:
  a1:
    a: 1
    b: 3
```

**Anything else you would like to add:**

Using `overlay.map_key` instead of `overlay.all` results in the same erroneous behaviour.
`overlay/merge` behaves as expected (does not replace key) with both matchers.

**Environment:**

- ytt version (use `ytt --version`): 0.51.1
- OS (e.g. from `/etc/os-release`): Windows 11 24H2 26100.3194

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joaopapereira** [comment]
Hey
Sorry for the delayed reply to this.
Not 100% sure here, but ytt looks like it is behaving as expected because you are matching inside the key `a` any value and replacing it, and by I,t I mean the full dict underneath the `#@overlay/replace` directive.
With the overlay merge ytt will find common keys and update those underneath the merge directive.
I was feedeling around a bit in the playground and I think that I have a solution for you.
```
a:
 a1:
   a: 1
   b: 2

#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.all
---
a:
#@overlay/match by=overlay.all, expects="1+"
 _:
  #@overlay/replace
   a: 1
   b: 3
```
in this example you see that the directive to relate is underneath the `_:` which tells ytt to replace using the next yaml block, this way the output is:
```yaml
a:
  a1:
    a: 1
    b: 3
```
